/* NEW YORKERS · THE MUSEUM. One hundred and eleven walkable New York rooms hung with the census. */
import { LANDMARK_ROOMS } from './rooms/y';
import * as T from 'three';
import { Kit } from './kit';
import { Fx } from './fx';
import { P, C, ERAS, FAMILIES, SETS, famName, thumb, fmt, era, hangList, hangLabel, atlasLoader, perAtlas, wallStart, placeCount, indexOf, DAY, CLOCK, HOUR, MINT, DEFAULT_HANG, trimAtlases, COLLECTOR } from './data';
import type { Hang, Piece } from './data';
import { textureBudget, beginRoom, trimCache } from './textures';
import type { EggData } from './kit';
import { ROOMS } from './rooms';
import { NEW_WORKING_ROOMS } from './rooms/x';
const newRoomIds = new Set([...NEW_WORKING_ROOMS,...LANDMARK_ROOMS].map(r => r.id));
import type { Mount } from './kit';
import type { RoomBuild } from './rooms/types';

const $ = <E extends HTMLElement = HTMLElement>(s: string) => document.querySelector(s) as E;
/* Sourced history per room (assets/rooms.js, generated by _build/build_learn.py). Optional: the museum runs without it. */
type RoomFact = { id: string; fact?: string; year?: string; learn?: string; article?: string; source?: { name: string; url: string } };
const FACTS: Record<string, RoomFact> = {};
for (const r of ((window as unknown as { NY_ROOMS?: RoomFact[] }).NY_ROOMS || [])) FACTS[r.id] = r;
const FIRST_ROOMS = ['metgreathall', 'bowery', 'cloisters'];
const START_ROOMS = [...FIRST_ROOMS, 'guggenheim', 'grand', 'brooklyn'];
const roomThumb = (id: string) => `assets/museum/rooms/${id}.jpg`;
const CFG = (window as unknown as { NY_CONFIG?: Record<string, string> }).NY_CONFIG || {};
let spinOnEnter = false;
/* the room a #room= link asked for, so the entrance keeps it in view */
let roomFromHash = '';
const esc = (s: string) => String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;');
const reducedQuery = matchMedia('(prefers-reduced-motion: reduce)');
const touch = matchMedia('(pointer: coarse)').matches;
const params = new URLSearchParams(location.search);
const quality: 'high' | 'low' = params.get('q') === 'low' || (touch && innerWidth < 900) || (navigator.hardwareConcurrency || 8) <= 4 ? 'low' : 'high';
const reduced = () => reducedQuery.matches || params.get('motion') === 'off';

type State = { room: number; hang: Hang; page: number; active: number; tour: boolean };
const state: State = { room: ROOMS.findIndex(r => r.id === 'metgreathall'), hang: { ...DEFAULT_HANG }, page: 0, active: -1, tour: false };
let renderer: T.WebGLRenderer | null = null;
let fx: Fx | null = null;
let kit: Kit | null = null;
let scene: T.Scene | null = null;
let camera: T.PerspectiveCamera;
let build: RoomBuild | null = null;
let list: Piece[] = [];
let shown: Piece[] = [];
let mountsFilled: (T.Group | null)[] = [];   // null where a mount was too small to hang, index stays aligned with shown[]
let frame = 0;
const atlas = atlasLoader(quality);

/* ---------- a collector's own hang ---------- */
const short = (a: string) => a.slice(0, 6) + '\u2026' + a.slice(-4);
/* Resolves hang=collector:<wallet or ENS> against the snapshot the collectors page is built from.
   Resolves to false when the wallet holds nothing, so the caller can fall back to the room's own hang. */
async function ensureCollector(key: string): Promise<boolean> {
  key = key.trim().toLowerCase();
  if (COLLECTOR.key === key && COLLECTOR.a) return true;
  try {
    let a = key;
    if (!/^0x[0-9a-f]{40}$/.test(key)) {
      const idx: Record<string, string> = await (await fetch('api/c/index.json')).json();
      a = Object.keys(idx).find((x) => (idx[x] || '').toLowerCase() === key) || '';
      if (!a) return false;
    }
    const r = await fetch(`api/c/${a}.json`);
    if (!r.ok) return false;
    const d = await r.json();
    COLLECTOR.key = key; COLLECTOR.a = a; COLLECTOR.name = d.ens || short(a); COLLECTOR.tag = d.tag || ''; COLLECTOR.home = d.home || '';
    COLLECTOR.nums = (d.pieces || []).filter((p: { id?: string; n?: number }) => p.id && p.n).map((p: { n: number }) => p.n);
    return COLLECTOR.nums.length > 0;
  } catch { return false; }
}
function collectorReady(): Promise<void> {
  if (state.hang.mode !== 'collector' || !state.hang.key) return Promise.resolve();
  return ensureCollector(state.hang.key).then((ok) => { if (!ok) state.hang = { mode: 'place' }; });
}

/* ---------- hash ---------- */
function readHash() {
  const h = new URLSearchParams(location.hash.replace(/^#/, ''));
  const want = MINT.room || h.get('room');
  if (want === 'random' || params.has('spin')) {
    state.room = Math.floor(Math.random() * ROOMS.length);
    spinOnEnter = true;
  } else {
    const r = ROOMS.findIndex((x) => x.id === want);
    if (r >= 0) { state.room = r; roomFromHash = ROOMS[r].id; }
  }
  // a batch export runs one room per page load so renderer memory starts fresh every time
  if (params.get('export') === 'all') state.room = Math.min(ROOMS.length - 1, Math.max(0, Number(params.get('from') || 0)));
  const hang = h.get('hang');
  if (!hang && newRoomIds.has(ROOMS[state.room].id)) state.hang = { mode: 'place' };
  if (hang) {
    const [mode, ...rest] = hang.split(':');
    state.hang = { mode: mode as Hang['mode'], key: rest.join(':') || undefined };
  }
  state.page = Math.max(0, Number(h.get('page') || 0) - 1 || 0);
  return h.get('n');
}
function writeHash() {
  const h = new URLSearchParams();
  h.set('room', ROOMS[state.room].id);
  if (state.hang.mode !== 'place') h.set('hang', state.hang.mode + (state.hang.key ? ':' + state.hang.key : ''));
  if (state.page) h.set('page', String(state.page + 1));
  history.replaceState(null, '', '#' + h.toString());
}

/* ---------- renderer ---------- */
function makeRenderer() {
  const host = $('#world');
  const r = new T.WebGLRenderer({ antialias: quality === 'high', powerPreference: quality === 'low' ? 'low-power' : 'high-performance' });
  r.setPixelRatio(Math.min(devicePixelRatio, quality === 'high' ? 1.75 : 1.2));
  r.setSize(host.clientWidth, host.clientHeight);
  r.outputColorSpace = T.SRGBColorSpace;
  r.toneMapping = T.ACESFilmicToneMapping;
  r.toneMappingExposure = 1.05;
  if (quality === 'high') {
    r.shadowMap.enabled = true;
    r.shadowMap.type = T.PCFSoftShadowMap;
  }
  host.appendChild(r.domElement);
  /* iOS drops the WebGL context when a tab runs out of graphics memory, and the room goes black with
     no error. Say what happened and offer the one fix that always works. */
  r.domElement.addEventListener('webglcontextlost', (e) => { e.preventDefault(); $('#lost').hidden = false; });
  /* Near at 0.5 rather than 0.1. The skyline needs the far plane at 1200, and a
     12,000 to 1 depth range leaves almost no precision in the twenty metres the
     visitor is actually standing in, which is what the occlusion pass reads. The
     collision model keeps them further than half a metre from anything anyway. */
  camera = new T.PerspectiveCamera(62, host.clientWidth / host.clientHeight, 0.5, 1200);
  addEventListener('resize', () => {
    camera.aspect = host.clientWidth / host.clientHeight;
    camera.updateProjectionMatrix();
    r.setSize(host.clientWidth, host.clientHeight);
    fx?.setSize(host.clientWidth, host.clientHeight);
  });
  return r;
}

/* ---------- camera + movement ---------- */
let yaw = 0,
  pitch = 0,
  pathIndex = 0,
  targetPath = 0,
  goal: T.Vector3 | null = null,
  lookGoal: T.Vector3 | null = null,
  waypoints: T.Vector3[] = [];
const keys = new Set<string>();
const touchDir = { f: 0, s: 0 };
function constrain() {
  if (!build) return;
  const [minX, maxX, minZ, maxZ] = build.bounds;
  camera.position.x = T.MathUtils.clamp(camera.position.x, minX, maxX);
  camera.position.z = T.MathUtils.clamp(camera.position.z, minZ, maxZ);
  for (const k of kit!.keepOut) {
    const dx = camera.position.x - k.x,
      dz = camera.position.z - k.z,
      d = Math.hypot(dx, dz);
    if (d < k.r && d > 0.0001) {
      camera.position.x = k.x + (dx / d) * k.r;
      camera.position.z = k.z + (dz / d) * k.r;
    }
  }
  for (const b of kit!.blocks) {
    const { x, z } = camera.position;
    if (x > b.x0 && x < b.x1 && z > b.z0 && z < b.z1) {
      const dx0 = x - b.x0, dx1 = b.x1 - x, dz0 = z - b.z0, dz1 = b.z1 - z;
      const m = Math.min(dx0, dx1, dz0, dz1);
      if (m === dx0) camera.position.x = b.x0;
      else if (m === dx1) camera.position.x = b.x1;
      else if (m === dz0) camera.position.z = b.z0;
      else camera.position.z = b.z1;
    }
  }
  camera.position.y = (build.floorY ? build.floorY(camera.position.x, camera.position.z) : 0) + build.eye;
}
function placeOnPath() {
  const p = build!.path!;
  const lo = Math.floor(pathIndex),
    hi = Math.min(lo + 1, p.length - 1);
  camera.position.lerpVectors(p[lo], p[hi], pathIndex - lo);
}
/* Is this a spot a visitor could actually be left standing? constrain() will
   shove the camera out of a block or a keep out and clamp it to the bounds, so
   a viewing position inside one of those is a position the visitor can never
   hold, and the work in front of them is unreachable. */
function standable(p: T.Vector3) {
  if (!build || !kit) return false;
  const [minX, maxX, minZ, maxZ] = build.bounds;
  if (p.x < minX || p.x > maxX || p.z < minZ || p.z > maxZ) return false;
  for (const b of kit.blocks) if (p.x > b.x0 && p.x < b.x1 && p.z > b.z0 && p.z < b.z1) return false;
  for (const k of kit.keepOut) if (Math.hypot(p.x - k.x, p.z - k.z) < k.r) return false;
  return true;
}

/* ---------- getting from here to there ----------

   The tour and a tap on the floor used to walk in a straight line and let
   constrain() stop them. In any room with an inner wall, a counter or a row of
   shelves that left the visitor pressed against the wall, facing a work on the
   other side of it. A headless walk of all 180 rooms (the same lerp, the same
   constrain) found 649 of 3,658 tour stops ending stuck or looking at a wall,
   in 105 rooms. So each room now gets a coarse floor grid of the places a
   visitor can stand, a little clear of every wall, and a walk that cannot go
   straight is routed round on it. A tight margin, because some rooms open onto
   the next through a doorway well under a metre wide. */
const NAV_CELL = 0.2, NAV_MARGIN = 0.08;
let nav: { x0: number; z0: number; w: number; h: number; free: Uint8Array; reach: Uint8Array } | null = null;
function roomy(x: number, z: number) {
  const g = NAV_MARGIN, [minX, maxX, minZ, maxZ] = build!.bounds;
  if (x < minX + g || x > maxX - g || z < minZ + g || z > maxZ - g) return false;
  for (const b of kit!.blocks) if (x > b.x0 - g && x < b.x1 + g && z > b.z0 - g && z < b.z1 + g) return false;
  for (const k of kit!.keepOut) if (Math.hypot(x - k.x, z - k.z) < k.r + g) return false;
  return true;
}
function buildNav() {
  nav = null;
  waypoints = [];
  if (!build || !kit || build.path) return;
  const [x0, x1, z0, z1] = build.bounds;
  const w = Math.ceil((x1 - x0) / NAV_CELL) + 1, h = Math.ceil((z1 - z0) / NAV_CELL) + 1;
  if (w * h > 4e6) return;   // a room this big walks straight, as before
  const free = new Uint8Array(w * h), reach = new Uint8Array(w * h);
  /* stamp each obstacle onto the cells it covers rather than test every cell against every obstacle */
  const g = NAV_MARGIN, C = NAV_CELL;
  for (let j = 0; j < h; j++) for (let i = 0; i < w; i++) {
    const x = x0 + i * C, z = z0 + j * C;
    free[j * w + i] = x >= x0 + g && x <= x1 - g && z >= z0 + g && z <= z1 - g ? 1 : 0;
  }
  const stamp = (ax: number, bx: number, az: number, bz: number, hit: (x: number, z: number) => boolean) => {
    const i0 = Math.max(0, Math.floor((ax - x0) / C)), i1 = Math.min(w - 1, Math.ceil((bx - x0) / C));
    const j0 = Math.max(0, Math.floor((az - z0) / C)), j1 = Math.min(h - 1, Math.ceil((bz - z0) / C));
    for (let j = j0; j <= j1; j++) for (let i = i0; i <= i1; i++) if (hit(x0 + i * C, z0 + j * C)) free[j * w + i] = 0;
  };
  for (const b of kit.blocks) stamp(b.x0 - g, b.x1 + g, b.z0 - g, b.z1 + g, (x, z) => x > b.x0 - g && x < b.x1 + g && z > b.z0 - g && z < b.z1 + g);
  for (const k of kit.keepOut) { const r = k.r + g; stamp(k.x - r, k.x + r, k.z - r, k.z + r, (x, z) => Math.hypot(x - k.x, z - k.z) < r); }
  nav = { x0, z0, w, h, free, reach };
  /* everywhere a visitor can get to from the door, so the tour never picks a spot they could not walk to */
  const s0 = navCell(build.spawn);
  if (s0 >= 0) {
    const st = [s0];
    reach[s0] = 1;
    while (st.length) {
      const c = st.pop()!, ci = c % w, cj = (c / w) | 0;
      for (const [di, dj] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) {
        const a = ci + di, b = cj + dj, n = b * w + a;
        if (a >= 0 && b >= 0 && a < w && b < h && free[n] && !reach[n]) { reach[n] = 1; st.push(n); }
      }
    }
  }
}
/* the free cell nearest a point, searching a little way out if the point itself is too close to a wall */
function navCell(p: { x: number; z: number }) {
  if (!nav) return -1;
  const { x0, z0, w, h, free } = nav;
  const i = T.MathUtils.clamp(Math.round((p.x - x0) / NAV_CELL), 0, w - 1), j = T.MathUtils.clamp(Math.round((p.z - z0) / NAV_CELL), 0, h - 1);
  if (free[j * w + i]) return j * w + i;
  let best = -1, bd = Infinity;
  for (let r = 1; r < 10 && best < 0; r++)
    for (let dj = -r; dj <= r; dj++)
      for (let di = -r; di <= r; di++) {
        const a = i + di, b = j + dj;
        if (a < 0 || b < 0 || a >= w || b >= h || !free[b * w + a]) continue;
        const d = di * di + dj * dj;
        if (d < bd) { bd = d; best = b * w + a; }
      }
  return best;
}
function reachable(p: T.Vector3) {
  if (!nav) return true;
  const c = navCell(p);
  return c >= 0 && nav.reach[c] === 1;
}
function segFree(a: { x: number; z: number }, b: { x: number; z: number }) {
  const n = Math.max(1, Math.ceil(Math.hypot(b.x - a.x, b.z - a.z) / 0.1));
  for (let i = 1; i < n; i++) if (!roomy(a.x + ((b.x - a.x) * i) / n, a.z + ((b.z - a.z) * i) / n)) return false;
  return true;
}
/* Can the visitor at `a` see the work at `m`? Only walls count (blocks), and not
   the wall the work itself hangs on. */
function sightClear(a: { x: number; z: number }, m: Mount) {
  const b = m.position, g = 0.35;
  const host = kit!.blocks.filter((q) => b.x > q.x0 - g && b.x < q.x1 + g && b.z > q.z0 - g && b.z < q.z1 + g);
  const n = Math.ceil(Math.hypot(b.x - a.x, b.z - a.z) / 0.2);
  for (let i = 1; i < n - 2; i++) {
    const x = a.x + ((b.x - a.x) * i) / n, z = a.z + ((b.z - a.z) * i) / n;
    for (const q of kit!.blocks) if (!host.includes(q) && x > q.x0 && x < q.x1 && z > q.z0 && z < q.z1) return false;
  }
  return true;
}
/* The turns on the way from one spot to another, the last of them being `to`.
   A straight walk when nothing is in the way, an A* route on the floor grid,
   pulled taut, when something is. Null when there is no way through. */
function route(from: T.Vector3, to: T.Vector3): T.Vector3[] | null {
  if (!nav || segFree(from, to)) return [to];
  const { x0, z0, w, h, free } = nav;
  const s0 = navCell(from), g0 = navCell(to);
  if (s0 < 0 || g0 < 0) return null;
  const gx = g0 % w, gz = (g0 / w) | 0;
  const cost = new Float32Array(w * h).fill(Infinity), prev = new Int32Array(w * h).fill(-1), done = new Uint8Array(w * h);
  const heap: [number, number][] = [];
  const push = (f: number, n: number) => {
    heap.push([f, n]);
    for (let i = heap.length - 1; i; ) { const pa = (i - 1) >> 1; if (heap[pa][0] <= heap[i][0]) break; [heap[pa], heap[i]] = [heap[i], heap[pa]]; i = pa; }
  };
  const pop = () => {
    const top = heap[0], last = heap.pop()!;
    if (heap.length) {
      heap[0] = last;
      for (let i = 0; ; ) {
        const l = 2 * i + 1, r = l + 1;
        let m = i;
        if (l < heap.length && heap[l][0] < heap[m][0]) m = l;
        if (r < heap.length && heap[r][0] < heap[m][0]) m = r;
        if (m === i) break;
        [heap[m], heap[i]] = [heap[i], heap[m]];
        i = m;
      }
    }
    return top[1];
  };
  cost[s0] = 0;
  push(0, s0);
  while (heap.length) {
    const c = pop();
    if (done[c]) continue;
    done[c] = 1;
    if (c === g0) break;
    const ci = c % w, cj = (c / w) | 0;
    for (let dj = -1; dj <= 1; dj++)
      for (let di = -1; di <= 1; di++) {
        if (!di && !dj) continue;
        const a = ci + di, b = cj + dj;
        if (a < 0 || b < 0 || a >= w || b >= h) continue;
        const n = b * w + a;
        if (!free[n] || (di && dj && (!free[cj * w + a] || !free[b * w + ci]))) continue;
        const nc = cost[c] + (di && dj ? Math.SQRT2 : 1);
        if (nc < cost[n]) { cost[n] = nc; prev[n] = c; push(nc + Math.hypot(a - gx, b - gz), n); }
      }
  }
  if (g0 !== s0 && prev[g0] < 0) return null;
  const cells: T.Vector3[] = [];
  for (let c = g0; c !== s0 && c >= 0; c = prev[c]) cells.unshift(new T.Vector3(x0 + (c % w) * NAV_CELL, 0, z0 + ((c / w) | 0) * NAV_CELL));
  cells.push(to);
  /* pull the string: keep only the corners a straight line cannot cut */
  const out: T.Vector3[] = [];
  let cur: { x: number; z: number } = from;
  for (let q = 0; q < cells.length; q++) if (q === cells.length - 1 || !segFree(cur, cells[q + 1])) { out.push(cells[q]); cur = cells[q]; }
  return out;
}
/* Set off for `dest`, routed round anything in the way. */
function setGoal(dest: T.Vector3) {
  goal = dest;
  waypoints = [];
  if (build && !build.path) {
    const r = route(camera.position, dest);
    if (r) waypoints = r.slice(0, -1).map((q) => new T.Vector3(q.x, (build!.floorY ? build!.floorY(q.x, q.z) : 0) + build!.eye, q.z));
  }
}

/* Where to stand to see mount n.

   The hand written target is used whenever it is any good, because it carries
   the room's intent: an angle the architect chose, a spot on a balcony. But an
   audit of all 111 rooms found 376 targets sitting inside a block, a keep out
   or outside the room's own bounds, and 234 works whose face pointed away from
   the place the visitor was being sent. Rather than leave those unviewable,
   fall back to the one position that is always right for a picture: straight
   out in front of it, far enough back to see it, at the first distance that is
   actually standable. */
function viewpoint(m: Mount) {
  const back = Math.max(3, (m.width || 4) * 0.9);
  const nx = Math.sin(m.rotation), nz = Math.cos(m.rotation);
  const toTarget = new T.Vector3().subVectors(m.target, m.position);
  const inFront = toTarget.x * nx + toTarget.z * nz > 0;
  const good = (p: T.Vector3) => standable(p) && reachable(p) && sightClear(p, m);
  if (inFront && good(m.target)) return m.target.clone();
  let fallback: T.Vector3 | null = inFront && standable(m.target) ? m.target.clone() : null;
  /* Search the floor in front of the work: straight out first, then further
     back, then off to either side. A picture in a corner or on a narrow
     landing often has nothing directly in front of it but plenty at an angle,
     and looking at a painting from off to one side is normal. */
  for (const d of [back, back * 1.4, back * 0.7, back * 1.9, back * 2.5, back * 3.2, back * 0.5, back * 4.2]) {
    for (const a of [0, 0.3, -0.3, 0.6, -0.6, 0.95, -0.95, 1.25, -1.25, 1.45, -1.45]) {
      const ax = Math.sin(m.rotation + a), az = Math.cos(m.rotation + a);
      const p = new T.Vector3(m.position.x + ax * d, m.target.y, m.position.z + az * d);
      if (good(p)) return p;
      if (!fallback && standable(p)) fallback = p;
    }
  }
  if (fallback) return fallback;
  /* Nothing in front of it is standable. Keep the authored target rather than
     inventing a worse one, and let constrain() do what it can. */
  return m.target.clone();
}

function focus(n: number) {
  if (!build || !build.mounts[n]) return;
  const m = build.mounts[n];
  const stand = viewpoint(m);
  setGoal(stand);
  lookGoal = (m.lookAt || m.position).clone();
  if (build.path) targetPath = nearestPath(stand);
  state.active = n;
  paintStrip();
}
function nearestPath(p: T.Vector3) {
  const path = build!.path!;
  let best = 0,
    bd = Infinity;
  path.forEach((q, i) => {
    const d = q.distanceToSquared(p);
    if (d < bd) {
      bd = d;
      best = i;
    }
  });
  return best;
}
function home() {
  if (!build) return;
  setGoal(build.spawn.clone());
  lookGoal = build.look.clone();
  targetPath = 0;
  state.active = -1;
  paintStrip();
}
function step(dir: number) {
  if (!build) return;
  goal = null;
  if (build.path) {
    pathIndex = T.MathUtils.clamp(pathIndex + dir * 4, 0, build.path.length - 1);
    placeOnPath();
  } else {
    camera.translateZ(-dir * 3);
    constrain();
  }
}

/* One tap, three meanings, settled by the first thing the ray meets: a landmark egg, a work, or the
   floor, which walks you there. Anything else in front (a wall, a counter, a person) swallows the tap,
   which is what stops an egg on the far side of a wall being found through it. Glass, washes, glints
   and particles are see through to the ray, as they are to the eye. */
const ray = new T.Raycaster();
function tap(x: number, y: number): string {
  if (!scene || !kit) return 'no room';
  ray.setFromCamera(new T.Vector2(x, y), camera);
  ray.far = 240;
  for (const h of ray.intersectObject(scene, true)) {
    const o = h.object as T.Mesh;
    const u = o.userData;
    if (u.egg) { openEgg(u.egg as EggData); return 'egg ' + (u.egg as EggData).id; }
    const kind = o as unknown as { isSprite?: boolean; isPoints?: boolean; isLine?: boolean };
    if (!o.visible || kind.isSprite || kind.isPoints || kind.isLine) continue;
    const mat = Array.isArray(o.material) ? o.material[0] : o.material;
    if (!mat || mat.transparent || !mat.visible) continue;
    if (u.piece) {
      if (u.mountIndex != null) state.active = u.mountIndex;
      openDetail(u.piece as Piece);
      return 'work';
    }
    if (u.tiles && h.faceIndex != null) {
      const gi = u.tiles[Math.floor(h.faceIndex / 2)];
      if (P[gi]) openDetail(P[gi]);
      return 'wall tile';
    }
    const n = h.face ? h.face.normal.clone().transformDirection(o.matrixWorld) : null;
    if (n && n.y > 0.7 && h.point.y < camera.position.y - 0.4) return walkTo(h.point) ? 'walk' : 'floor out of reach';
    const col = (mat as T.MeshBasicMaterial).color ? '#' + (mat as T.MeshBasicMaterial).color.getHexString() : '?';
    return `blocked by ${o.type} ${o.geometry.type} ${col}${(mat as T.MeshBasicMaterial).map ? ' textured' : ''} at ${h.distance.toFixed(1)} m, point ${h.point.toArray().map((q) => q.toFixed(1)).join(',')}, normal y ${n ? n.y.toFixed(2) : '?'}`;
  }
  return 'nothing';
}
/* Walk to a spot. One the visitor could never stand on (inside a counter, past a railing) is pulled
   back toward them until it is somewhere they can. Returns false when nowhere on the line is. */
function walkTo(p: T.Vector3, look?: T.Vector3) {
  if (!build) return false;
  const dest = new T.Vector3(p.x, 0, p.z);
  if (build.path) {
    targetPath = nearestPath(dest);
    dest.copy(build.path[targetPath]);
  } else {
    const from = new T.Vector3(camera.position.x, 0, camera.position.z);
    for (let i = 0; i < 14 && !standable(dest); i++) dest.lerp(from, 0.18);
    if (!standable(dest)) return false;
    dest.y = (build.floorY ? build.floorY(dest.x, dest.z) : 0) + build.eye;
  }
  lookGoal = look ? look.clone() : dest.clone().addScaledVector(camera.getWorldDirection(new T.Vector3()), 10);
  setGoal(dest);
  state.tour = false;
  paintTour();
  showMarker(p.x, p.y, p.z);
  return true;
}
/* The ring that answers a tap on the floor, so the visitor sees where they are going. */
let marker: T.Mesh | null = null, markerT = 0;
function showMarker(x: number, y: number, z: number) {
  if (!marker) return;
  marker.position.set(x, y + 0.04, z);
  marker.visible = true;
  markerT = 1;
}

function bindControls(canvas: HTMLCanvasElement) {
  let lookId = -1,
    lastX = 0,
    lastY = 0,
    moved = 0;
  const sens = touch ? 1.4 : 1;
  canvas.tabIndex = 0;
  canvas.setAttribute('aria-label', 'Walkable gallery. Drag to look, W A S D to walk, J for the next artwork. Tap the floor to walk there, tap a glint to find a landmark.');
  canvas.addEventListener('pointerdown', (e) => {
    if (lookId !== -1) return;           // a second finger on the room is ignored, so the view never jumps
    canvas.focus();
    lookId = e.pointerId;
    lastX = e.clientX;
    lastY = e.clientY;
    moved = 0;
    try { canvas.setPointerCapture(e.pointerId); } catch { /* some webviews refuse; the drag still works while the finger stays on the canvas */ }
  });
  canvas.addEventListener('pointermove', (e) => {
    if (e.pointerId !== lookId) return;
    const dx = e.clientX - lastX,
      dy = e.clientY - lastY;
    moved += Math.abs(dx) + Math.abs(dy);
    yaw -= dx * 0.0042 * sens;
    pitch = T.MathUtils.clamp(pitch - dy * 0.0032 * sens, -0.9, 0.9);
    lastX = e.clientX;
    lastY = e.clientY;
    if (moved > 3) goal = null;
  });
  canvas.addEventListener('pointercancel', (e) => { if (e.pointerId === lookId) lookId = -1; });
  canvas.addEventListener('pointerup', (e) => {
    if (e.pointerId !== lookId) return;
    lookId = -1;
    if (moved > (touch ? 12 : 7)) return;
    const rect = canvas.getBoundingClientRect();
    tap(((e.clientX - rect.left) / rect.width) * 2 - 1, (-(e.clientY - rect.top) / rect.height) * 2 + 1);
  });
  bindStick();
  canvas.addEventListener('wheel', (e) => {
    if (!build) return;
    e.preventDefault();
    step(e.deltaY < 0 ? 0.5 : -0.5);
  }, { passive: false });
  addEventListener('keydown', (e) => {
    const t = e.target as HTMLElement;
    if (t.closest('input,textarea,[contenteditable]')) return;
    if (e.key === 'Escape') {
      closePanels();
      return;
    }
    if (document.querySelector('.panel.open,#detail.open,#egg.open')) return;
    if (e.key === 'Enter' && t.closest('button,a,summary')) return;
    if (['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'w', 'a', 's', 'd', 'W', 'A', 'S', 'D', 'Shift'].includes(e.key)) {
      e.preventDefault();
      keys.add(e.key.toLowerCase());
      goal = null;
    }
    if (e.key.toLowerCase() === 'j' && build && !t.closest('button,a,summary') && !document.querySelector('.panel.open,#detail.open,#egg.open')) {
      e.preventDefault();
      focus((state.active + (e.shiftKey ? -1 : 1) + build.mounts.length) % build.mounts.length);
    }
    if (e.key === 'Enter' && state.active >= 0 && shown[state.active] && !$('#detail').classList.contains('open')) openDetail(shown[state.active]);
    if (e.key === 'h' || e.key === 'H') home();
    if (e.key === 'r' || e.key === 'R') spin();
    if (e.key === 'p' || e.key === 'P') takeSnap();
  });
  addEventListener('keyup', (e) => keys.delete(e.key.toLowerCase()));
  addEventListener('blur', () => keys.clear());
}
/* The thumb stick replaces the four button pad. How far you push is how fast you walk, so a small
   push creeps up to a picture and a full push crosses the room. It owns its own finger, so the other
   thumb can look around at the same time. */
function bindStick() {
  const stick = $('#stick'), knob = stick.querySelector('i') as HTMLElement;
  const R = 44, dead = 0.14;
  let id = -1, cx = 0, cy = 0;
  const move = (e: PointerEvent) => {
    let dx = e.clientX - cx, dy = e.clientY - cy;
    const d = Math.hypot(dx, dy);
    if (d > R) { dx *= R / d; dy *= R / d; }
    knob.style.transform = `translate(${dx}px,${dy}px)`;
    const mx = dx / R, my = dy / R;
    touchDir.s = Math.abs(mx) < dead ? 0 : mx;
    touchDir.f = Math.abs(my) < dead ? 0 : -my;
  };
  stick.addEventListener('pointerdown', (e) => {
    if (id !== -1) return;
    e.preventDefault();
    id = e.pointerId;
    try { stick.setPointerCapture(e.pointerId); } catch { /* as above */ }
    const r = stick.getBoundingClientRect();
    cx = r.left + r.width / 2;
    cy = r.top + r.height / 2;
    stick.classList.add('on');
    goal = null;
    if (state.tour) { state.tour = false; paintTour(); }
    move(e);
  });
  stick.addEventListener('pointermove', (e) => { if (e.pointerId === id) move(e); });
  const end = (e: PointerEvent) => {
    if (e.pointerId !== id) return;
    id = -1;
    touchDir.f = touchDir.s = 0;
    knob.style.transform = '';
    stick.classList.remove('on');
  };
  stick.addEventListener('pointerup', end);
  stick.addEventListener('pointercancel', end);
  stick.addEventListener('lostpointercapture', end);
}

/* ---------- landmark eggs ---------- */
/* Found eggs live in their own key, apart from the site eggs (ny_eggs), so the site hunt keeps its count. */
const EGG_KEY = 'ny_landmarks';
const eggFound = new Set<string>((() => { try { return JSON.parse(localStorage.getItem(EGG_KEY) || '[]') as string[]; } catch { return []; } })());
const eggKey = (id: string) => ROOMS[state.room].id + ':' + id;
function openEgg(d: EggData) {
  const key = eggKey(d.id);
  const first = !eggFound.has(key);
  if (first) {
    eggFound.add(key);
    try { localStorage.setItem(EGG_KEY, JSON.stringify([...eggFound])); } catch { /* private window: the hunt still works for this visit */ }
  }
  kit?.markEggs((id) => eggFound.has(eggKey(id)));
  const n = kit?.eggs.length || 0, got = kit ? kit.eggs.filter((e) => e.found).length : 0;
  const def = ROOMS[state.room];
  $('#eggKick').textContent = `${first ? 'LANDMARK FOUND' : 'LANDMARK'} · ${got} OF ${n} IN THIS ROOM`;
  $('#eggTitle').textContent = d.title;
  $('#eggYear').textContent = (d.year ? d.year + ' · ' : '') + def.area;
  $('#eggText').textContent = d.text;
  const src = $('#eggSource') as HTMLAnchorElement;
  src.href = d.source.url;
  src.textContent = 'SOURCE: ' + d.source.name.toUpperCase() + ' ↗';
  const ri = d.room ? ROOMS.findIndex((r) => r.id === d.room) : -1;
  const go = $('#eggRoom') as HTMLButtonElement;
  go.hidden = ri < 0 || ri === state.room || !!MINT.room;
  if (ri >= 0) { go.textContent = 'WALK TO ' + ROOMS[ri].name.toUpperCase(); go.onclick = () => { closePanels(); setRoom(ri); }; }
  ($('#eggShare') as HTMLButtonElement).onclick = () => share({ title: `${d.title} · THE MUSEUM`, text: `I found ${d.title} hidden in ${def.name} in THE MUSEUM by MLow. ${n} real New York landmarks hide in this room. Your turn.`, url: roomUrl(state.room) });
  closePanels();
  panelReturn = document.activeElement as HTMLElement;
  $('#egg').classList.add('open');
  keys.clear(); touchDir.f = touchDir.s = 0;
  paintEggChip(first);
  try { document.dispatchEvent(new CustomEvent('ny:landmark', { detail: { key, first, count: eggFound.size } })); } catch { /* old browsers */ }
}
function paintEggChip(pop = false) {
  const chip = $('#eggChip');
  const n = kit?.eggs.length || 0;
  chip.hidden = !n;
  if (!n) return;
  const got = kit!.eggs.filter((e) => e.found).length;
  chip.innerHTML = got === n ? `✦ <b>${n}/${n}</b> ALL FOUND` : `✦ <b>${got}/${n}</b> LANDMARKS`;
  if (pop) { chip.classList.remove('pop'); void chip.offsetWidth; chip.classList.add('pop'); }
}
function paintEggList() {
  if (!kit) return;
  $('#eggTotal').textContent = `${eggFound.size} FOUND ACROSS THE MUSEUM`;
  const list = $('#eggList');
  list.textContent = '';
  for (const e of kit.eggs) {
    const row = document.createElement('div');
    row.className = 'row' + (e.found ? ' found' : '');
    const b = document.createElement('b');
    b.textContent = e.found ? e.data.title : 'Not found yet';
    const p = document.createElement('p');
    p.textContent = e.found ? (e.data.year ? e.data.year + '. ' : '') + e.data.text : 'Clue: ' + e.data.clue;
    const btn = document.createElement('button');
    btn.textContent = e.found ? 'READ IT AGAIN' : 'WALK ME CLOSER';
    btn.onclick = () => { closePanels(); if (e.found) openEgg(e.data); else guideTo(e); };
    row.append(b, p, btn);
    list.appendChild(row);
  }
}
/* A clue that is still too hard: walk the visitor to a few paces short of the egg and turn them to
   face it. They still have to tap it themselves. */
function guideTo(e: { center: T.Vector3; r?: number }) {
  const away = new T.Vector3(camera.position.x - e.center.x, 0, camera.position.z - e.center.z);
  if (away.lengthSq() < 1e-4) away.set(0, 0, 1);
  away.normalize();
  const stand = e.center.clone().addScaledVector(away, 3.5 + Math.min(e.r ?? 1, 2));
  if (!walkTo(stand, e.center)) { goal = camera.position.clone(); lookGoal = e.center.clone(); }
}

/* ---------- the loop ---------- */
/* The post chain is worth roughly nothing on a fast desktop and could be worth
   everything on a weak phone, and I could not measure it reliably anywhere. So
   the museum measures itself: it watches real frame times once the chain is
   running and drops back to plain rendering if the room cannot hold the budget.
   Better a museum that looks slightly flatter than one that stutters. */
const FX_BUDGET_MS = 22;          // below about 45 fps
const FX_WARMUP_FRAMES = 45;      // shaders compile and textures upload first
const FX_SAMPLE_FRAMES = 90;
let fxFrames = 0, fxAcc = 0, fxJudged = false;
/* The low path measures itself too. A phone that cannot hold about 30 fps at its pixel ratio steps
   down, twice at most, and never steps back up, so the view cannot pump. */
let drFrames = 0, drAcc = 0, stall = 0;
const TOUR_DWELL = 6.5;
let tourClock = 0;
let prev = performance.now();
function animate(now: number) {
  frame = requestAnimationFrame(animate);
  if (!renderer || !scene || !build || !kit) { prev = now; return; }
  // Do not gate the draw on document.hidden. requestAnimationFrame is already
  // paused by the browser in a background tab, and embedded viewers (previews,
  // in-app webviews) report hidden while still painting, which left the room
  // pure black. Gate the setInterval tour instead, where it actually matters.
  const raw = now - prev;
  const dt = Math.min(raw / 1000, 0.05);
  prev = now;
  if (fx && !fxJudged) {
    fxFrames++;
    if (fxFrames > FX_WARMUP_FRAMES) fxAcc += raw;
    if (fxFrames >= FX_WARMUP_FRAMES + FX_SAMPLE_FRAMES) {
      const mean = fxAcc / FX_SAMPLE_FRAMES;
      fxJudged = true;
      if (mean > FX_BUDGET_MS) {
        fx = null;
        console.info(`[museum] post chain off: ${mean.toFixed(1)} ms a frame, over the ${FX_BUDGET_MS} ms budget`);
      } else {
        console.info(`[museum] post chain on: ${mean.toFixed(1)} ms a frame`);
      }
    }
  }
  if (quality === 'low' && raw < 250) {
    drFrames++;
    if (drFrames > 60) drAcc += raw;
    if (drFrames >= 150) {
      const mean = drAcc / 90, pr = renderer.getPixelRatio();
      drFrames = 0; drAcc = 0;
      if (mean > 30 && pr > 0.8) {
        const host = $('#world');
        renderer.setPixelRatio(Math.max(0.75, pr - 0.2));
        renderer.setSize(host.clientWidth, host.clientHeight);
        console.info(`[museum] ${mean.toFixed(1)} ms a frame, pixel ratio down to ${renderer.getPixelRatio().toFixed(2)}`);
      }
    }
  }
  if (state.tour && shown.length && !document.querySelector('.panel.open,#detail.open,#egg.open')) {
    /* the dwell starts when the visitor arrives, so a long walk does not eat the looking */
    if (!goal) tourClock += dt;
    if (tourClock >= TOUR_DWELL) { tourClock = 0; focus(nextHung(state.active)); }
  } else {
    tourClock = 0;
  }
  if (goal && lookGoal) {
    const before = camera.position.clone();
    if (reduced()) {
      waypoints = [];
      camera.position.copy(goal);
      if (build.path) { pathIndex = targetPath; placeOnPath(); }
      camera.lookAt(lookGoal);
    }
    if (build.path) {
      pathIndex += (targetPath - pathIndex) * (1 - Math.exp(-dt * 2.2));
      if (Math.abs(pathIndex - targetPath) < 0.02) pathIndex = targetPath;
      placeOnPath();
    } else if (waypoints.length) {
      /* walking a route: an even pace from corner to corner, eyes on the way ahead */
      const w = waypoints[0], d = Math.hypot(w.x - camera.position.x, w.z - camera.position.z);
      const step = Math.min(d, dt * 3.4);
      if (d > 1e-4) camera.position.add(new T.Vector3((w.x - camera.position.x) / d * step, 0, (w.z - camera.position.z) / d * step));
      if (d < 0.15) waypoints.shift();
    } else camera.position.lerp(goal, 1 - Math.exp(-dt * 3));
    const ahead = waypoints.length ? new T.Vector3(waypoints[0].x, camera.position.y, waypoints[0].z) : null;
    const looking = ahead && ahead.distanceToSquared(camera.position) > 0.04 ? ahead : lookGoal;
    const m = new T.Matrix4().lookAt(camera.position, looking, new T.Vector3(0, 1, 0));
    const tq = new T.Quaternion().setFromRotationMatrix(m);
    camera.quaternion.slerp(tq, 1 - Math.exp(-dt * 4));
    const e = new T.Euler().setFromQuaternion(camera.quaternion, 'YXZ');
    yaw = e.y;
    pitch = e.x;
    if (!build.path) constrain();
    /* arrived means there and facing the right way; a walk that a wall has stopped short also ends */
    const turned = camera.quaternion.angleTo(tq) < 0.01;
    stall = camera.position.distanceToSquared(before) < 1e-7 ? stall + 1 : 0;
    if ((turned && !waypoints.length && (build.path ? Math.abs(pathIndex - targetPath) < 0.02 : camera.position.distanceTo(goal) < 0.03)) || stall > 40) { goal = null; waypoints = []; stall = 0; }
  } else {
    camera.rotation.set(pitch, yaw, 0, 'YXZ');
    const push = touchDir.f * touchDir.f + touchDir.s * touchDir.s;
    const run = keys.has('shift') ? 1.8 : push > 0.9 ? 1.3 : 1;
    const f = T.MathUtils.clamp((keys.has('w') || keys.has('arrowup') ? 1 : 0) - (keys.has('s') || keys.has('arrowdown') ? 1 : 0) + touchDir.f, -1, 1);
    const s = T.MathUtils.clamp((keys.has('d') || keys.has('arrowright') ? 1 : 0) - (keys.has('a') || keys.has('arrowleft') ? 1 : 0) + touchDir.s, -1, 1);
    const mag = Math.min(1, Math.hypot(f, s));
    if (build.path) {
      if (f) {
        pathIndex = T.MathUtils.clamp(pathIndex + f * dt * 18 * run, 0, build.path.length - 1);
        placeOnPath();
      }
    } else if (mag > 0) {
      const speed = dt * 7 * run * mag;
      const dir = new T.Vector3(s, 0, -f).normalize().applyAxisAngle(new T.Vector3(0, 1, 0), yaw);
      camera.position.addScaledVector(dir, speed);
      constrain();
    }
  }
  if (!reduced()) kit.tick(now / 1000, dt);
  if (marker && markerT > 0) {
    markerT = Math.max(0, markerT - dt * 0.8);
    (marker.material as T.MeshBasicMaterial).opacity = markerT * 0.85;
    marker.scale.setScalar(1 + (1 - markerT) * 0.9);
    if (!markerT) marker.visible = false;
  }
  /* renderer.info resets on every render() call, so read after the composer's last quad it says calls 1, tris 0k.
     Reset it here once per frame instead; the count then covers the whole frame (shadow, scene and fx passes). */
  renderer.info.autoReset = false;
  renderer.info.reset();
  if (fx) fx.render(); else renderer.render(scene, camera);
  /* SNAP reads the canvas in the same task as the draw: without preserveDrawingBuffer the buffer is gone after compositing. */
  if (snapWant) { snapWant = false; captureSnap(); }
  if (params.has('debug')) $('#debug').textContent = `calls ${renderer.info.render.calls} · tris ${(renderer.info.render.triangles / 1000).toFixed(0)}k · tex ${renderer.info.memory.textures} · geo ${renderer.info.memory.geometries}`;
}

/* ---------- rooms ---------- */
function loadRoom(openN?: string | null): Promise<void> {
  const def = ROOMS[state.room];
  $('#loading').textContent = 'BUILDING ' + def.area;
  $('#loading').classList.add('show');
  return new Promise((done) => setTimeout(() => {
    if (kit) kit.dispose();
    kit = null;
    scene = new T.Scene();
    const dynamic = def.daylit !== false && !params.has('fixed');
    kit = new Kit(scene, { renderer: renderer!, quality, reduced: reduced(), atlas, atlasGrid: C.atlasGrid, perAtlas, hour: HOUR, dynamic });
    list = hangList(state.hang, def.id);
    const ctx = { pieces: list, all: P, thumb, reduced: reduced(), quality, wallStart, page: state.page };
    beginRoom();
    build = def.build(kit, ctx);
    /* The post chain outlives the room, so it is built once and repointed at
       each new scene. High path only, and `?fx=off` turns it off entirely. */
    if (quality === 'high' && params.get('fx') !== 'off') {
      const host = $('#world');
      if (!fx) fx = new Fx(renderer!, scene, camera, host.clientWidth || 1280, host.clientHeight || 720, params.get('fx') || '');
      else fx.setScene(scene, camera);
      /* Judge again in the new room, because the next one may be far heavier
         than the one that passed. Once the chain is off it stays off, so this
         cannot flap on and off around the budget. */
      if (fx) { fxFrames = 0; fxAcc = 0; fxJudged = false; }
    }
    /* A work whose face points away from the place the room sends you to see it
       from is simply hung backwards: you arrive behind the picture. The target
       carries the room's intent, so turning the work to face it is the faithful
       correction, and it costs nothing when the room is already right. An audit
       of all 111 rooms found 224 of 2,335 works hung this way, twenty of the
       twenty two in the bleachers and every one of the twenty five at Liberty. */
    for (const m of build.mounts) {
      const dx = m.target.x - m.position.x, dz = m.target.z - m.position.z;
      if (dx * Math.sin(m.rotation) + dz * Math.cos(m.rotation) < 0) m.rotation += Math.PI;
    }
    buildNav();
    kit.brand(build, def.name);
    const n = build.mounts.length;
    const pages = Math.max(1, Math.ceil(list.length / n));
    state.page = Math.min(state.page, pages - 1);
    shown = list.slice(state.page * n, state.page * n + n);
    mountsFilled = [];
    shown.forEach((p, i) => {
      const m = build!.mounts[i];
      const er = era(p);
      const cap = [fmt(p), p.t.length > 44 ? p.t.slice(0, 43) + '…' : p.t, `ERA ${er?.roman || p.e} · ${famName(p.f).toUpperCase()} · ${(p.nb || p.b || '').toUpperCase()}`];
      mountsFilled.push(kit!.hang(m, p, m.style || build!.style, i, thumb(p), cap));
    });
    kit.batch();
    kit.markEggs((id) => eggFound.has(def.id + ':' + id));
    marker = new T.Mesh(new T.RingGeometry(0.28, 0.4, 40), new T.MeshBasicMaterial({ color: 0x00e5ff, transparent: true, opacity: 0, depthWrite: false }));
    marker.rotation.x = -Math.PI / 2;
    marker.visible = false;
    marker.renderOrder = 2;
    scene.add(marker);
    markerT = 0;
    /* phones: let go of every surface and atlas sheet this room does not use */
    if (quality === 'low') { trimCache(); trimAtlases(kit.used.atlases); }
    camera.position.copy(build.spawn);
    camera.lookAt(build.look);
    const e = new T.Euler().setFromQuaternion(camera.quaternion, 'YXZ');
    yaw = e.y;
    pitch = e.x;
    pathIndex = targetPath = 0;
    goal = null;
    state.active = -1;
    paintHud(pages);
    writeHash();
    /* record the visit against a collector profile, if there is one. Never blocks the room. */
    try {
      fetch('/api/event', { method: 'POST', credentials: 'same-origin',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ kind: 'room', key: def.id }) }).catch(() => {});
    } catch { /* logged out, or offline: the museum does not care */ }
    $('#loading').classList.remove('show');
    if (snapOnReady) { snapOnReady = false; setTimeout(takeSnap, 1500); }
    if (openN) {
      const p = P[indexOf.get(openN) ?? -1];
      if (p) openDetail(p);
    }
    done();
  }, 30));
}
function setRoom(i: number) {
  state.room = i;
  if (newRoomIds.has(ROOMS[i].id) && state.hang.mode === 'launch') state.hang = { mode: 'place' };
  state.page = 0;
  state.tour = false;
  return loadRoom();
}
function setHang(h: Hang) {
  state.hang = h;
  state.page = 0;
  loadRoom();
}
function setPage(p: number) {
  state.page = p;
  loadRoom();
}

/* ---------- HUD ---------- */
function paintHud(pages: number) {
  const def = ROOMS[state.room];
  $('#roomArea').textContent = def.area;
  $('#roomName').textContent = def.name;
  $('#roomMood').textContent = def.mood.toUpperCase() + ' · NYC ' + String(state.room + 1).padStart(2, '0') + ' / ' + ROOMS.length;
  $('#hangLabel').textContent = hangLabel(state.hang, def.area);
  const f = FACTS[def.id];
  const factEl = $('#roomFact');
  if (factEl) {
    if (f && (f.learn || f.fact)) {
      factEl.hidden = false;
      factEl.innerHTML = `<span>${esc(f.learn || f.fact || '')}</span> <a href="${f.article ? 'learn/' + f.article + '.html' : 'rooms/' + def.id + '.html'}" target="_blank" rel="noopener">THE HISTORY ↗</a>`;
    } else factEl.hidden = true;
  }
  $('#dyn').textContent = `${DAY} · ${CLOCK} NEW YORK · ${def.daylit === false ? 'FIXED HOUR' : kit && kit.night > 0.5 ? 'NIGHT LIGHT' : kit && kit.dusk > 0.3 ? 'DUSK LIGHT' : 'DAYLIGHT'} · HANG OF THE DAY`;
  $('#pageLabel').innerHTML = `${String(state.page + 1).padStart(2, '0')}<small> / ${String(pages).padStart(2, '0')}</small>`;
  ($('#pagePrev') as HTMLButtonElement).disabled = state.page === 0;
  ($('#pageNext') as HTMLButtonElement).disabled = state.page >= pages - 1;
  $('#hint').textContent = touch
    ? (build?.path ? 'DRAG TO LOOK · STICK FOLLOWS THE ROUTE · TAP A WORK OR A GLINT' : 'DRAG TO LOOK · STICK OR TAP THE FLOOR TO WALK · TAP A GLINT')
    : (build?.path ? 'DRAG TO LOOK · W/S FOLLOW THE ROUTE · CLICK A WORK OR A GLINT' : 'DRAG TO LOOK · WASD OR CLICK THE FLOOR · CLICK A GLINT');
  $('#count').textContent = `${list.length.toLocaleString('en-US')} WORKS IN THIS HANG · ${C.pieces.toLocaleString('en-US')} IN THE CENSUS`;
  paintStrip();
  paintEggChip();
  document.title = `NEW YORKERS · The Museum · ${def.area}`;
}
function paintStrip() {
  const el = $('#strip');
  el.innerHTML = shown.map((p, i) => `<button class="${state.active === i ? 'on' : ''}" data-i="${i}" aria-label="Go to ${esc(p.t)}"><img loading="lazy" src="${thumb(p)}" alt=""><span>${String(p.n).padStart(4, '0')}</span></button>`).join('');
  el.querySelectorAll('button').forEach((b) => (b.onclick = () => focus(Number(b.dataset.i))));
  const on = el.querySelector('button.on') as HTMLElement | null;
  if ($('#artTray')?.hasAttribute('open')) on?.scrollIntoView({ block: 'nearest', inline: 'center', behavior: reduced() ? 'auto' : 'smooth' });
}

let panelReturn: HTMLElement | null = null;
function closePanels() {
  document.querySelectorAll('.panel.open').forEach((p) => p.classList.remove('open'));
  $('#detail').classList.remove('open');
  $('#egg').classList.remove('open');
  if (!spinning) $('#slot')?.classList.remove('open');
  panelReturn?.focus(); panelReturn = null;
}
function openPanel(id: string) {
  const was = $(id).classList.contains('open');
  closePanels();
  if (!was) {
    panelReturn = document.activeElement as HTMLElement;
    $(id).classList.add('open');
    keys.clear(); touchDir.f = touchDir.s = 0;
    $(id).querySelector<HTMLElement>('input,button')?.focus();
  }
}

/* ---------- detail ---------- */
/* ORDER A PRINT. assets/prints.js (window.NY_PRINTS) is the one switch for prints across the
   site: unless it says live there is no button, exactly as on the piece pages. A Keystone work
   whose own product is live (assets/keystone_prints.js, window.NY_KEYSTONE_PRINTS) goes straight
   to that product at the shop. Every other work, and a Keystone work while its product is still
   a draft, goes to its own record page's order block, where the size and the surface are chosen
   and the piece number rides on the cart line. Extensionless, because Pages 308s the .html form. */
type PrintSwitch = { status?: string; shop?: string; pieces?: Record<string, { handle?: string }> };
function printHref(p: Piece): string {
  const w = window as unknown as { NY_PRINTS?: PrintSwitch; NY_KEYSTONE_PRINTS?: PrintSwitch };
  if (!w.NY_PRINTS || w.NY_PRINTS.status !== 'live' || p.n == null) return '';
  const ks = w.NY_KEYSTONE_PRINTS;
  const handle = ks && ks.status === 'live' && ks.pieces ? ks.pieces[String(p.n)]?.handle : '';
  if (handle) return `${(ks!.shop || 'https://mlow.nyc').replace(/\/+$/, '')}/products/${encodeURIComponent(handle)}`;
  return `n/${encodeURIComponent(p.id)}#orderbox`;
}
function openDetail(p: Piece) {
  const er = era(p);
  const d = $('#detail');
  d.querySelector('img')!.setAttribute('src', thumb(p));
  $('#dNum').textContent = fmt(p);
  $('#dTitle').textContent = p.t;
  $('#dMeta').innerHTML = `ERA ${er?.roman || p.e} · ${esc(er?.title || '')}<br>${esc(famName(p.f).toUpperCase())} · ${esc((p.b || '').toUpperCase())}${p.nb ? ' · ' + esc(p.nb.toUpperCase()) : ''}${p.set ? '<br>SET · ' + esc(p.set.toUpperCase()) : ''}`;
  $('#dStory').textContent = p.story || '';
  // Canal Street: cycle the real piece, its knockoff, and any bootleg takes; never the default
  const canal = $('#dCanal') as HTMLButtonElement | null;
  if (canal) {
    const cs = p.cs;
    const views = cs ? [{ key: p.st[0], title: p.t, label: 'CANAL STREET' }, { key: cs.k, title: cs.name, label: 'THE REAL ONE' }, ...(cs.x || []).map((k, i, a) => ({ key: k, title: cs.name + (a.length > 1 ? ' · BOOTLEG ' + (i + 1) : ' · BOOTLEG'), label: 'THE REAL ONE' }))] : [];
    let vi = 0;
    canal.hidden = !cs;
    canal.textContent = 'CANAL STREET';
    canal.onclick = () => {
      vi = (vi + 1) % views.length;
      const v = views[vi];
      d.querySelector('img')!.setAttribute('src', `assets/t/${v.key}.jpg`);
      $('#dTitle').textContent = v.title;
      canal.textContent = vi === views.length - 1 ? 'THE REAL ONE' : 'NEXT KNOCKOFF';
      if (vi === 0) canal.textContent = 'CANAL STREET';
    };
  }
  ($('#dRecord') as HTMLAnchorElement).href = `census.html#n=${p.id}`;
  const dShare = $('#dShare') as HTMLButtonElement | null;
  if (dShare) dShare.onclick = () => share({ title: `${fmt(p)} · ${p.t}`, text: `${fmt(p)} · ${p.t}. ${p.story || ''} NEW YORKERS by MLow, hanging in ${ROOMS[state.room].name}.`, url: `${location.origin}${location.pathname.replace(/museum\.html$/, '')}census.html#n=${p.id}` });
  ($('#dAtlas') as HTMLAnchorElement).href = `map.html#p=${p.id}`;
  const dPrint = $('#dPrint') as HTMLAnchorElement | null;
  if (dPrint) {
    const href = printHref(p);
    dPrint.hidden = !href;
    dPrint.href = href || '#';
  }
  const i = shown.indexOf(p);
  const go = $('#dGo') as HTMLButtonElement;
  go.hidden = i < 0;
  go.onclick = () => {
    focus(i);
    d.classList.remove('open');
  };
  const hangHere = $('#dHang') as HTMLButtonElement;
  hangHere.hidden = i >= 0;
  hangHere.onclick = () => {
    const gi = list.indexOf(p);
    if (gi >= 0) {
      d.classList.remove('open');
      setPage(Math.floor(gi / build!.mounts.length));
      setTimeout(() => focus(gi % build!.mounts.length), 400);
    } else {
      setHang({ mode: 'search', key: String(p.n) });
      d.classList.remove('open');
    }
  };
  d.classList.add('open');
}

/* ---------- panels ---------- */
function buildPanels() {
  $('#destGrid').innerHTML = ROOMS.map((r, i) => `<button data-i="${i}" style="--c:${r.color}"><span class="pic"><img loading="lazy" src="${roomThumb(r.id)}" alt="${esc(r.name)}"><span class="num">${String(i + 1).padStart(2, '0')}</span>${FACTS[r.id]?.year ? `<span class="yr">${esc(FACTS[r.id].year!)}</span>` : ''}</span><span class="txt"><small>${esc(r.area)}</small><strong>${esc(r.name)}</strong><p>${esc(r.description)}</p><em>${esc(r.mood)} · ${placeCount(r.id).toLocaleString('en-US')} ${newRoomIds.has(r.id) ? 'thematically matched' : 'recorded here'}</em></span></button>`).join('');
  $('#destGrid').querySelectorAll('button').forEach((b) => (b.onclick = () => { closePanels(); setRoom(Number(b.dataset.i)); }));
  const q = $('#destSearch') as HTMLInputElement | null;
  let roomFilter = 'start';
  const filterRooms = () => {
    const v = q?.value.trim().toLowerCase() || '';
    let found = 0;
    $('#destGrid').querySelectorAll<HTMLButtonElement>('button').forEach((b) => {
      const r = ROOMS[Number(b.dataset.i)];
      const matches = v ? (r.name + ' ' + r.area + ' ' + r.description + ' ' + r.mood).toLowerCase().includes(v) : roomFilter === 'all' || (roomFilter === 'landmarks' ? LANDMARK_ROOMS.some(n=>n.id===r.id) : roomFilter === 'new' ? NEW_WORKING_ROOMS.some(n=>n.id===r.id) : START_ROOMS.includes(r.id));
      b.hidden = !matches;
      if (matches) found++;
    });
    $('#destResult').textContent = found ? `${found} rooms${v ? ' found' : roomFilter === 'start' ? ' to start with' : ' to explore'}` : 'No rooms found. Try a neighborhood or clear your search.';
  };
  if (q) q.oninput = filterRooms;
  document.querySelectorAll<HTMLButtonElement>('#destFilters button').forEach(b => b.onclick = () => {
    roomFilter = b.dataset.filter!;
    document.querySelectorAll('#destFilters button').forEach(x => x.setAttribute('aria-pressed', String(x === b)));
    filterRooms();
  });
  filterRooms();
  const chip = (h: Hang, label: string, sub = '') => `<button class="chip" data-h="${h.mode}${h.key ? ':' + h.key : ''}"><b>${esc(label)}</b>${sub ? `<span>${esc(sub)}</span>` : ''}</button>`;
  $('#hangTop').innerHTML = chip({ mode: 'launch' }, 'THE TWELVE', 'the launch fortnight, Sept 8 to 21, then this place') + chip({ mode: 'place' }, 'This place', 'the New Yorkers recorded at this location') + chip({ mode: 'all' }, 'The whole census', `${C.pieces.toLocaleString('en-US')} works by number`) + chip({ mode: 'heroes' }, 'The heroes', 'the hundred marks and closers');
  $('#hangEras').innerHTML = ERAS.map((e) => chip({ mode: 'era', key: String(e.i) }, `ERA ${e.roman}`, e.title)).join('');
  $('#hangFamilies').innerHTML = FAMILIES.map((f) => chip({ mode: 'family', key: f }, famName(f), `${P.filter((p) => p.f === f).length}`)).join('');
  $('#hangSets').innerHTML = SETS.map((s) => chip({ mode: 'set', key: s }, s, `${P.filter((p) => p.set === s).length}`)).join('');
  document.querySelectorAll<HTMLButtonElement>('#hang .chip').forEach((b) => (b.onclick = () => {
    const [mode, ...rest] = b.dataset.h!.split(':');
    closePanels();
    setHang({ mode: mode as Hang['mode'], key: rest.join(':') || undefined });
  }));
  const search = $('#search') as HTMLInputElement;
  $('#searchGo').onclick = () => { closePanels(); setHang({ mode: 'search', key: search.value }); };
  search.addEventListener('keydown', (e) => { if (e.key === 'Enter') { closePanels(); setHang({ mode: 'search', key: search.value }); } });
}
let indexShown = 0;
function paintIndex(reset = false) {
  const grid = $('#indexGrid');
  if (reset) {
    grid.innerHTML = '';
    indexShown = 0;
    $('#indexTitle').textContent = hangLabel(state.hang, ROOMS[state.room].area);
    $('#indexCount').textContent = list.length.toLocaleString('en-US') + ' WORKS';
  }
  const slice = list.slice(indexShown, indexShown + 240);
  const frag = document.createDocumentFragment();
  slice.forEach((p, k) => {
    const gi = indexShown + k;
    const b = document.createElement('button');
    b.innerHTML = `<img loading="lazy" src="${thumb(p)}" alt=""><span class="n">${fmt(p)}</span><span class="t">${esc(p.t)}</span>`;
    b.onclick = () => {
      closePanels();
      const n = build!.mounts.length;
      const pg = Math.floor(gi / n);
      if (pg !== state.page) {
        setPage(pg);
        setTimeout(() => { focus(gi % n); openDetail(p); }, 500);
      } else {
        focus(gi % n);
        openDetail(p);
      }
    };
    frag.appendChild(b);
  });
  grid.appendChild(frag);
  indexShown += slice.length;
  ($('#indexMore') as HTMLButtonElement).hidden = indexShown >= list.length;
}

/* ---------- export: the room as a GLB, the view as a poster ---------- */
const wait = (ms: number) => new Promise((r) => setTimeout(r, ms));
async function send(post: string, name: string, body: Blob | string) {
  const res = await fetch(post, { method: 'POST', headers: { 'X-Name': name }, body });
  if (!res.ok) throw new Error('export receiver refused ' + name);
}
function download(name: string, blob: Blob) {
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = name;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => { URL.revokeObjectURL(a.href); a.remove(); }, 8000);
}
async function exportRoom(post?: string | null) {
  if (!kit || !build || !renderer) return null;
  const def = ROOMS[state.room];
  const name = `new-yorkers-museum-${String(state.room + 1).padStart(2, '0')}-${def.id}`;
  $('#loading').textContent = 'WAITING FOR TEXTURES';
  $('#loading').classList.add('show');
  await kit.settled();
  await wait(600);
  $('#loading').textContent = 'EXPORTING ' + def.area;
  kit.showGlints(false);
  if (marker) marker.visible = false;
  const poster = await kit.poster(camera);
  const glb = await kit.exportGLB(Number(params.get('tex') || 1024));
  kit.showGlints(true);
  const info = { id: def.id, index: state.room + 1, assets: { atlases: [...kit.used.atlases], thumbs: [...kit.used.thumbs], props: [...kit.used.props], images: [...kit.used.images] }, name: def.name, area: def.area, mood: def.mood, description: def.description, signatures: def.signatures, daylit: def.daylit !== false, day: DAY, hour: HOUR, hang: shown.map((p) => ({ n: p.n, id: p.id, t: p.t })), mounts: build.mounts.length, calls: renderer.info.render.calls, triangles: renderer.info.render.triangles, glbBytes: glb.size };
  if (post) {
    await send(post, name + '.png', poster);
    await send(post, name + '.glb', glb);
    await send(post, name + '.json', JSON.stringify(info, null, 1));
  } else {
    download(name + '.glb', glb);
  }
  $('#loading').classList.remove('show');
  return info;
}
/* One room per page load: export, then replace the URL with from=i+1 and let the page reload. A failed room is retried once. */
async function exportChain(post: string, i: number) {
  let ok = false;
  try { ok = !!(await exportRoom(post)); } catch (e) { console.error('export failed', ROOMS[i].id, e); $('#loading').classList.remove('show'); }
  const tries = Number(params.get('retry') || 0);
  const giveUp = !ok && tries >= 2;
  if (giveUp) { await send(post, `FAILED-${ROOMS[i].id}.txt`, `export failed three times`); }
  const next = ok || giveUp ? i + 1 : i;
  const to = Math.min(ROOMS.length - 1, Number(params.get('to') ?? ROOMS.length - 1));
  if (next > to) { await send(post, to >= ROOMS.length - 1 ? 'done.txt' : `chunk-${to}.txt`, `${DAY} ${CLOCK} rooms through ${to + 1}`); $('#loading').textContent = 'EXPORT CHUNK COMPLETE'; $('#loading').classList.add('show'); return; }
  const u = new URL(location.href);
  u.searchParams.set('from', String(next));
  if (ok || giveUp) u.searchParams.delete('retry'); else u.searchParams.set('retry', String(tries + 1));
  u.searchParams.set('v', String(Date.now()));
  u.hash = '';
  await wait(400);
  location.replace(u.toString());
}
async function exportAll(post: string) {
  const manifest: unknown[] = [];
  for (let i = 0; i < ROOMS.length; i++) {
    await setRoom(i);
    manifest.push(await exportRoom(post));
    await wait(300);
  }
  await send(post, 'manifest.json', JSON.stringify({ day: DAY, hour: HOUR, rooms: manifest }, null, 1));
  $('#loading').textContent = 'EXPORTED ' + ROOMS.length + ' ROOMS';
  $('#loading').classList.add('show');
}

/* ---------- share ---------- */
function shareUrl(u: string) {
  try { const x = new URL(u, location.href); if (!x.searchParams.get('ref')) x.searchParams.set('ref', 'share'); return x.toString(); } catch { return u; }
}
async function share(o: { title: string; text: string; url: string }) {
  const url = shareUrl(o.url);
  const nav = navigator as Navigator & { share?: (d: { title: string; text: string; url: string }) => Promise<void> };
  if (nav.share) { try { await nav.share({ title: o.title, text: o.text, url }); return; } catch (e) { if ((e as Error).name === 'AbortError') return; } }
  try { await navigator.clipboard.writeText(o.text + ' ' + url); flash('LINK COPIED'); } catch { flash(url); }
}
function flash(msg: string) {
  const el = $('#loading');
  el.textContent = msg; el.classList.add('show');
  setTimeout(() => el.classList.remove('show'), 1400);
}
function roomUrl(i: number) { return `${location.origin}${location.pathname}#room=${ROOMS[i].id}`; }
function shareRoom() {
  const def = ROOMS[state.room];
  share({ title: `${def.name} · THE MUSEUM · NEW YORKERS by MLow`, text: `I am standing in ${def.name} (${def.area}) in THE MUSEUM, ${ROOMS.length} walkable New York rooms hung with ${C.pieces.toLocaleString('en-US')} painted New Yorkers.`, url: roomUrl(state.room) });
}

/* ---------- SAVE IT, POST IT ---------- */
/* MLow 2026-10-04: collectors save the view they are standing in and post it on X. X intents cannot carry
   media, so SAVE hands over the picture and POST ON X carries the words and the link. Inside a minted
   room token (a marketplace iframe) downloads are usually sandboxed, so SAVE opens the same room on the
   site with #snap=1, which takes the picture there. */
let snapWant = false;
let snapBlob: Blob | null = null;
let snapOnReady = /(^|[#&])snap=1(&|$)/.test(location.hash);
const SITE = 'https://n3wyorkers.com';
const framed = (() => { try { return window.top !== window; } catch { return true; } })();
function takeSnap() { snapWant = true; }
function captureSnap() {
  if (!renderer) return;
  const src = renderer.domElement;
  const def = ROOMS[state.room];
  const k = Math.min(1, 2400 / src.width);
  const w = Math.round(src.width * k), h = Math.round(src.height * k), bar = Math.max(44, Math.round(w * 0.045));
  const c = document.createElement('canvas'); c.width = w; c.height = h + bar;
  const g = c.getContext('2d');
  if (!g) return;
  g.drawImage(src, 0, 0, w, h);
  g.fillStyle = '#0d0d0d'; g.fillRect(0, h, w, bar);
  const fs = Math.round(bar * 0.36), pad = Math.round(bar * 0.45), mid = h + bar / 2;
  g.textBaseline = 'middle'; g.fillStyle = '#fff';
  g.font = `800 ${fs}px "Space Grotesk", system-ui, sans-serif`;
  g.textAlign = 'left'; g.fillText(def.name.toUpperCase(), pad, mid);
  g.font = `500 ${Math.round(fs * 0.8)}px "IBM Plex Mono", ui-monospace, monospace`;
  g.textAlign = 'right'; g.fillText('NEW YORKERS BY MLOW · N3WYORKERS.COM', w - pad, mid);
  c.toBlob((b) => {
    if (!b) { flash('TRY AGAIN'); return; }
    snapBlob = b;
    const img = $('#snapImg') as HTMLImageElement;
    if (img.src.startsWith('blob:')) URL.revokeObjectURL(img.src);
    img.src = URL.createObjectURL(b);
    img.alt = def.name + ', THE MUSEUM';
    $('#snapTitle').textContent = def.name;
    $('#snapNote').textContent = framed ? 'SAVE opens this room on n3wyorkers.com, where the download works.' : '';
    if (!$('#snap').classList.contains('open')) openPanel('#snap');
  }, 'image/png');
}
function snapFile() { return `new-yorkers-museum-${ROOMS[state.room].id}.png`; }
async function snapSave() {
  if (framed) { window.open(`${SITE}/museum#room=${ROOMS[state.room].id}&snap=1`, '_blank', 'noopener'); return; }
  if (!snapBlob) return;
  const file = new File([snapBlob], snapFile(), { type: 'image/png' });
  const nav = navigator as Navigator & { canShare?: (d: { files: File[] }) => boolean; share?: (d: { files: File[]; title?: string }) => Promise<void> };
  if (touch && nav.canShare?.({ files: [file] }) && nav.share) {
    try { await nav.share({ files: [file], title: ROOMS[state.room].name }); return; } catch (e) { if ((e as Error).name === 'AbortError') return; }
  }
  const a = document.createElement('a');
  a.href = URL.createObjectURL(snapBlob); a.download = snapFile();
  document.body.appendChild(a); a.click(); a.remove();
  setTimeout(() => URL.revokeObjectURL(a.href), 4000);
  flash('SAVED');
}
function snapPost() {
  const def = ROOMS[state.room];
  const text = `I AM STANDING IN ${def.name.toUpperCase()}\n\nTHE MUSEUM, ${ROOMS.length} walkable New York rooms by MLow 🗽`;
  const url = `${SITE}/museum#room=${def.id}`;
  window.open(`https://x.com/intent/post?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`, '_blank', 'noopener');
}

/* ---------- the slot machine ---------- */
let spinning = false;
function spin(auto = false) {
  if (spinning) return;
  spinning = true;
  closePanels();
  const slot = $('#slot');
  const reel = $('#slotReel');
  const pick = (() => { let r = Math.floor(Math.random() * ROOMS.length); if (ROOMS.length > 1 && r === state.room) r = (r + 1 + Math.floor(Math.random() * (ROOMS.length - 1))) % ROOMS.length; return r; })();
  slot.classList.add('open');
  slot.classList.remove('landed');
  $('#slotTitle').textContent = 'SPINNING THE CITY';
  $('#slotSub').textContent = `${ROOMS.length} ROOMS · ONE PULL`;
  const acts = $('#slotActs'); acts.hidden = true;
  const total = reduced() ? 8 : 34;
  const seq: number[] = [];
  for (let k = 0; k < total - 1; k++) seq.push(Math.floor(Math.random() * ROOMS.length));
  seq.push(pick);
  let k = 0;
  const step = () => {
    const i = seq[k];
    const r = ROOMS[i];
    reel.innerHTML = `<img src="${roomThumb(r.id)}" alt=""><div class="cap"><small>${esc(r.area)}</small><b>${esc(r.name)}</b></div>`;
    k++;
    if (k < seq.length) {
      const t = 40 + Math.pow(k / seq.length, 3) * 420;
      setTimeout(step, t);
    } else land();
  };
  const land = () => {
    slot.classList.add('landed');
    const r = ROOMS[pick];
    $('#slotTitle').textContent = 'YOU LANDED IN';
    $('#slotSub').textContent = `${r.area} · ${placeCount(r.id).toLocaleString('en-US')} NEW YORKERS RECORDED HERE`;
    acts.hidden = false;
    spinning = false;
    ($('#slotGo') as HTMLButtonElement).onclick = () => { slot.classList.remove('open'); setRoom(pick); };
    ($('#slotAgain') as HTMLButtonElement).onclick = () => spin();
    ($('#slotShare') as HTMLButtonElement).onclick = () => share({ title: `I landed in ${r.name}`, text: `I pulled the lever on THE MUSEUM and landed in ${r.name} (${r.area}). ${ROOMS.length} New York rooms, ${C.pieces.toLocaleString('en-US')} painted New Yorkers. Your turn.`, url: `${location.origin}${location.pathname}#room=random` });
    if (auto) setTimeout(() => { if (slot.classList.contains('open') && !spinning) { slot.classList.remove('open'); setRoom(pick); } }, 2600);
  };
  step();
}

/* ---------- the entrance: three rooms, freshly dealt ---------- */
function sample<T>(arr: T[], n: number): T[] {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; }
  return a.slice(0, n);
}
/* Three rooms picked fresh on every arrival, out of all of them, so the door is
   never the same door twice. A #room= link keeps its room in the first slot. */
function dealFirstRooms(keep = '') {
  const rest = sample(ROOMS.filter(r => r.id !== keep).map(r => r.id), keep ? 2 : 3);
  const ids = keep ? [keep, ...rest] : rest;
  if (!keep) state.room = ROOMS.findIndex(r => r.id === ids[0]);
  const pressed = ROOMS[state.room].id;
  $('#firstRooms').innerHTML = ids.map(id => {
    const r = ROOMS.find(x => x.id === id)!;
    return `<button data-room="${id}" aria-pressed="${pressed === id}"><img src="${roomThumb(id)}" alt=""><strong>${esc(r.name)}</strong><small>${esc(r.mood)}</small></button>`;
  }).join('');
  document.querySelectorAll<HTMLButtonElement>('#firstRooms button').forEach(b => b.onclick = () => {
    state.room = ROOMS.findIndex(r => r.id === b.dataset.room);
    spinOnEnter = false;
    $('#enterRoom').textContent = 'FIRST STOP · ' + ROOMS[state.room].area;
    document.querySelectorAll('#firstRooms button').forEach(x => x.setAttribute('aria-pressed', String(x === b)));
  });
  if (!spinOnEnter) $('#enterRoom').textContent = 'FIRST STOP · ' + ROOMS[state.room].area;
}

/* ---------- boot ---------- */
function boot() {
  textureBudget(quality === 'low');
  const openN = readHash();
  buildPanels();
  dealFirstRooms(params.get('export') === 'all' ? ROOMS[state.room].id : roomFromHash);  // a batch export keeps the room it was sent to
  const reroll = $('#firstAgain') as HTMLButtonElement | null;
  if (reroll) reroll.onclick = () => { roomFromHash = ''; dealFirstRooms(); };
  $('#enterCount').innerHTML = `<b>${C.pieces.toLocaleString('en-US')}</b> NEW YORKERS · <b>${ROOMS.length}</b> ROOMS · <b>${C.eras}</b> ERAS`;
  $('#enterRoom').textContent = (spinOnEnter ? 'THE CITY WILL PICK YOUR ROOM' : 'FIRST STOP · ' + ROOMS[state.room].area);
  if (eggFound.size) $('#enterCount').innerHTML += ` · <b>${eggFound.size}</b> LANDMARKS FOUND`;
  const sub = $('#enterSub'); if (sub) sub.textContent = `${ROOMS.length} ROOMS · THE CITY IS THE GALLERY`;
  if (touch) document.body.classList.add('touch');
  $('#enterBtn').onclick = () => {
    $('#enterBtn').setAttribute('disabled', '');
    if (!renderer) {
      try {
        renderer = makeRenderer();
      } catch {
        $('#noGl').hidden = false;
        $('#enterBtn').removeAttribute('disabled');
        return;
      }
      bindControls(renderer.domElement);
      frame = requestAnimationFrame(animate);
    }
    collectorReady().then(() => loadRoom(openN)).then(() => {
      $('#enter').classList.add('gone');
      $('#enter').setAttribute('inert', '');
      $('#btnTour').focus();
      if (spinOnEnter) { spinOnEnter = false; spin(true); }
      // ?at=x,y,z&yaw=deg&pitch=deg: stand the camera somewhere for a review screenshot (debug only)
      const at = params.get('at');
      if (at && camera) { const [ax, ay, az] = at.split(',').map(Number); if ([ax, ay, az].every(Number.isFinite)) camera.position.set(ax, ay, az); yaw = (Number(params.get('yaw') || 0) * Math.PI) / 180; pitch = (Number(params.get('pitch') || 0) * Math.PI) / 180; }
      const post = params.get('post') || 'http://127.0.0.1:4181/';
      if (params.get('export') === 'all') exportChain(post, state.room);
      else if (params.get('export') === 'allinone') exportAll(post);
      else if (params.get('export') === 'one') exportRoom(post);
    });
  };
  /* no public GLB button: MLow 2026-10-01, the rooms are his work and are not handed out; ?export= still serves the mint pipeline */
  $('#btnSpin').onclick = () => spin();
  const enterSpin = $('#enterSpin') as HTMLButtonElement | null;
  if (enterSpin) enterSpin.onclick = () => { spinOnEnter = true; $('#enterBtn').click(); };
  $('#btnShare').onclick = shareRoom;
  $('#btnSnap').onclick = takeSnap;
  $('#snapSave').onclick = () => { snapSave(); };
  $('#snapPost').onclick = snapPost;
  $('#snapAgain').onclick = () => { closePanels(); setTimeout(takeSnap, 400); };
  $('#eggChip').onclick = () => { openPanel('#eggs'); paintEggList(); };
  $('#lostBtn').onclick = () => location.reload();
  if (!document.fullscreenEnabled) $('#btnFull').hidden = true;
  if (touch) document.addEventListener('gesturestart', (e) => e.preventDefault());
  const slotX = $('#slotClose') as HTMLButtonElement | null;
  if (slotX) slotX.onclick = () => { if (!spinning) $('#slot').classList.remove('open'); };
  $('#btnDest').onclick = () => openPanel('#dest');
  $('#btnHang').onclick = () => openPanel('#hang');
  $('#btnIndex').onclick = () => { openPanel('#index'); paintIndex(true); };
  $('#indexMore').onclick = () => paintIndex();
  $('#btnFull').onclick = () => { if (document.fullscreenElement) document.exitFullscreen(); else document.documentElement.requestFullscreen?.().catch(() => {}); };
  $('#btnHome').onclick = () => { home(); state.tour = false; paintTour(); };
  $('#btnTour').onclick = () => { state.tour = !state.tour; paintTour(); if (state.tour) { tourClock = 0; focus(nextHung(state.active)); } };
  $('#pagePrev').onclick = () => setPage(state.page - 1);
  $('#pageNext').onclick = () => setPage(state.page + 1);
  $('#stepF').onclick = () => step(1);
  $('#stepB').onclick = () => step(-1);
  $('#changeRoom').onclick = () => openPanel('#dest');
  document.querySelectorAll<HTMLElement>('[data-close]').forEach((b) => (b.onclick = closePanels));
  // The tour advances off the render loop, not a timer. requestAnimationFrame
  // stops in a real background tab, so the tour pauses there on its own, and it
  // keeps running in embedded viewers that report document.hidden while painting.

  addEventListener('hashchange', () => {
    const before = state.room + '|' + state.hang.mode + ':' + state.hang.key + '|' + state.page;
    const n = readHash();
    const after = state.room + '|' + state.hang.mode + ':' + state.hang.key + '|' + state.page;
    if (before !== after && renderer) collectorReady().then(() => loadRoom(n));
  });
  // a collector link says whose collection this is before anyone presses enter
  if (state.hang.mode === 'collector') collectorReady().then(() => {
    if (state.hang.mode !== 'collector') return;
    $('#enterRoom').textContent = 'THE COLLECTION OF ' + COLLECTOR.name.toUpperCase() + ' · ' + COLLECTOR.nums.length + ' NEW YORKERS · ' + ROOMS[state.room].area;
  });
  if (MINT.room) { $('#btnDest').hidden = true; $('#changeRoom').hidden = true; document.body.classList.add('minted'); }
  if (params.has('debug')) $('#debug').hidden = false;
  if (params.has('auto')) $('#enterBtn').click();
}
/* The next mount along that actually has a work on it. A mount too small to hang
   stays empty, and the tour used to stop in front of the bare wall. */
function nextHung(from: number) {
  const n = Math.max(1, shown.length);
  for (let k = 1; k <= n; k++) {
    const i = (from + k + n) % n;
    if (mountsFilled[i] !== null && build?.mounts[i]) return i;
  }
  return (from + 1 + n) % n;
}
function paintTour() {
  $('#btnTour').textContent = state.tour ? '❚❚ Pause tour' : '▶ Guided tour';
}
void frame;
(window as unknown as { __museum: unknown }).__museum = { state, get camera() { return camera; }, get kit() { return kit; }, get build() { return build; }, get renderer() { return renderer; }, get fx() { return fx; }, focus, tap, walkTo, openEgg, openDetail, setRoom, setHang, setPage, exportRoom, exportAll, spin, shareRoom, takeSnap, FACTS, ROOMS, DAY, HOUR };
boot();
