# -*- coding: utf-8 -*-
"""Hand-built NYC gazetteer for NEW YORKERS.
Each entry: (key, display, kind, borough, lat, lon, [patterns])
kind: landmark | park | venue | corridor | line | bridge | island | transit | institution | water
Patterns are lowercase substrings matched on word boundaries.
"""

LANDMARKS = [
 # ---------- Manhattan icons ----------
 ("empire_state","The Empire State Building","landmark","Manhattan",40.7484,-73.9857,["empire state"]),
 ("chrysler","The Chrysler Building","landmark","Manhattan",40.7516,-73.9755,["chrysler building"]),
 ("times_square","Times Square","landmark","Manhattan",40.7580,-73.9855,["times square","crossroads of the world","the ball drop","ball drop","new year's eve ball"]),
 ("rock_center","Rockefeller Center","landmark","Manhattan",40.7587,-73.9787,["rockefeller cent","30 rock","the rink at rock","radio city","rockettes","christmas tree lighting"]),
 ("msg","Madison Square Garden","venue","Manhattan",40.7505,-73.9934,["madison square garden","msg","knicks","rangers","the world's most famous arena"]),
 ("penn_station","Penn Station","transit","Manhattan",40.7506,-73.9935,["penn station","moynihan"]),
 ("grand_central","Grand Central Terminal","transit","Manhattan",40.7527,-73.9772,["grand central","the whispering gallery","celestial ceiling"]),
 ("port_authority","Port Authority Bus Terminal","transit","Manhattan",40.7570,-73.9903,["port authority"]),
 ("nypl","The New York Public Library","institution","Manhattan",40.7532,-73.9822,["public library","patience and fortitude","the lions on fifth"]),
 ("bryant","Bryant Park","park","Manhattan",40.7536,-73.9832,["bryant park"]),
 ("central_park","Central Park","park","Manhattan",40.7829,-73.9654,["central park","the ramble","bethesda","sheep meadow","the great lawn","strawberry fields","bow bridge","the reservoir","conservatory garden","central park zoo"]),
 ("met_museum","The Metropolitan Museum of Art","institution","Manhattan",40.7794,-73.9632,["metropolitan museum","the met steps","the met gala","met gala","the met museum"]),
 ("moma","MoMA","institution","Manhattan",40.7614,-73.9776,["moma","museum of modern art"]),
 ("guggenheim","The Guggenheim","institution","Manhattan",40.7830,-73.9590,["guggenheim"]),
 ("amnh","American Museum of Natural History","institution","Manhattan",40.7813,-73.9740,["natural history","the blue whale","hayden planetarium"]),
 ("whitney","The Whitney","institution","Manhattan",40.7396,-74.0089,["the whitney"]),
 ("lincoln_center","Lincoln Center","venue","Manhattan",40.7725,-73.9835,["lincoln center","the met opera","metropolitan opera","new york city ballet"]),
 ("carnegie","Carnegie Hall","venue","Manhattan",40.7651,-73.9799,["carnegie hall"]),
 ("apollo","The Apollo Theater","venue","Manhattan",40.8099,-73.9500,["apollo theater","the apollo","amateur night"]),
 ("cbgb","CBGB","venue","Manhattan",40.7255,-73.9920,["cbgb"]),
 ("studio54","Studio 54","venue","Manhattan",40.7632,-73.9838,["studio 54"]),
 ("chelsea_hotel","The Chelsea Hotel","landmark","Manhattan",40.7440,-73.9967,["chelsea hotel","hotel chelsea"]),
 ("plaza_hotel","The Plaza","landmark","Manhattan",40.7644,-73.9744,["the plaza hotel","the plaza"]),
 ("hotel_new_yorker","The Hotel New Yorker","landmark","Manhattan",40.7524,-73.9938,["hotel new yorker"]),
 ("stonewall","The Stonewall Inn","landmark","Manhattan",40.7340,-74.0021,["stonewall"]),
 ("washington_sq","Washington Square Park","park","Manhattan",40.7308,-73.9973,["washington square","the arch","the fountain in the square"]),
 ("union_sq","Union Square","landmark","Manhattan",40.7359,-73.9911,["union square","the greenmarket","union square greenmarket"]),
 ("madison_sq_park","Madison Square Park","park","Manhattan",40.7423,-73.9880,["madison square park","the flatiron","flatiron building","shake shack","shackburger"]),
 ("high_line","The High Line","park","Manhattan",40.7480,-74.0048,["high line"]),
 ("hudson_yards","Hudson Yards","landmark","Manhattan",40.7540,-74.0021,["hudson yards","the vessel"]),
 ("wall_street","Wall Street","corridor","Manhattan",40.7069,-74.0113,["wall street","the stock exchange","new york stock exchange","the charging bull","charging bull","the bull"]),
 ("wtc","One World Trade / Ground Zero","landmark","Manhattan",40.7127,-74.0134,["world trade","ground zero","twin towers","the oculus","tribute in light","september 11","9/11","the towers"]),
 ("city_hall","City Hall","institution","Manhattan",40.7128,-74.0060,["city hall","gracie mansion","the mayor's office"]),
 ("tammany","Tammany Hall","landmark","Manhattan",40.7338,-73.9903,["tammany"]),
 ("trump_tower","Trump Tower","landmark","Manhattan",40.7624,-73.9739,["trump tower"]),
 ("un","The United Nations","institution","Manhattan",40.7489,-73.9680,["united nations","the u.n."]),
 ("katzs","Katz's Delicatessen","venue","Manhattan",40.7223,-73.9874,["katz's","katzs"]),
 ("nathan_orchard","Orchard Street","corridor","Manhattan",40.7182,-73.9887,["orchard street","the tenement museum","tenement museum"]),
 ("bowery","The Bowery","corridor","Manhattan",40.7220,-73.9930,["the bowery","bowery"]),
 ("canal_st","Canal Street","corridor","Manhattan",40.7188,-74.0009,["canal street","canal st"]),
 ("delancey","Delancey Street","corridor","Manhattan",40.7184,-73.9880,["delancey"]),
 ("houston_st","Houston Street","corridor","Manhattan",40.7250,-73.9950,["houston street"]),
 ("fifth_ave","Fifth Avenue","corridor","Manhattan",40.7625,-73.9738,["fifth avenue","5th avenue","museum mile"]),
 ("madison_ave","Madison Avenue","corridor","Manhattan",40.7690,-73.9640,["madison avenue"]),
 ("park_ave","Park Avenue","corridor","Manhattan",40.7640,-73.9700,["park avenue"]),
 ("broadway","Broadway / The Theater District","corridor","Manhattan",40.7590,-73.9845,["broadway","the theater district","theatre district","the marquee","playbill","the great white way","opening night on broadway"]),
 ("ninth_ave","Ninth Avenue","corridor","Manhattan",40.7620,-73.9910,["ninth avenue","9th avenue"]),
 ("42nd_st","42nd Street","corridor","Manhattan",40.7560,-73.9900,["42nd street"]),
 ("14th_st","14th Street","corridor","Manhattan",40.7370,-73.9960,["14th street"]),
 ("125th_st","125th Street","corridor","Manhattan",40.8090,-73.9470,["125th street"]),
 ("53rd_6th","53rd and 6th","corridor","Manhattan",40.7610,-73.9790,["53rd and 6th","53rd & 6th"]),
 ("mannahatta","Mannahatta","landmark","Manhattan",40.7580,-73.9700,["mannahatta","lenape","the island of many hills"]),
 ("roosevelt_island","Roosevelt Island","island","Manhattan",40.7614,-73.9506,["roosevelt island","the tram","the aerial tram"]),
 ("randalls","Randall's Island","island","Manhattan",40.7930,-73.9210,["randall's island","randalls island"]),
 ("governors","Governors Island","island","Manhattan",40.6895,-74.0166,["governors island"]),
 ("ellis","Ellis Island","island","Manhattan",40.6995,-74.0396,["ellis island"]),
 ("liberty","The Statue of Liberty","landmark","Manhattan",40.6892,-74.0445,["statue of liberty","lady liberty","liberty island"]),
 ("battery","The Battery","park","Manhattan",40.7033,-74.0170,["the battery","battery park"]),
 ("south_st_seaport","South Street Seaport","landmark","Manhattan",40.7060,-74.0030,["seaport","fulton fish"]),
 ("stuy_town","Stuyvesant Town","landmark","Manhattan",40.7318,-73.9776,["stuyvesant town","stuy town","peter cooper village"]),
 ("columbia","Columbia University","institution","Manhattan",40.8075,-73.9626,["columbia university","morningside heights campus"]),
 ("nyu","NYU","institution","Manhattan",40.7295,-73.9965,["nyu","new york university"]),
 ("bellevue","Bellevue Hospital","institution","Manhattan",40.7392,-73.9757,["bellevue"]),
 ("harlem_hospital","Harlem","landmark","Manhattan",40.8116,-73.9465,["the harlem renaissance","harlem renaissance","striver's row","strivers row","sylvia's","lenox lounge","cotton club"]),
 ("sesame","Sesame Street","landmark","Manhattan",40.7860,-73.9770,["sesame street","oscar the grouch"]),
 ("sardis","Sardi's / Restaurant Row","venue","Manhattan",40.7590,-73.9860,["sardi's","restaurant row"]),
 ("55_bar","The Village Vanguard","venue","Manhattan",40.7368,-74.0014,["village vanguard","the vanguard","blue note"]),
 ("52nd_street","52nd Street (Swing Street)","corridor","Manhattan",40.7600,-73.9800,["52nd street","swing street"]),
 ("canyon_heroes","The Canyon of Heroes","corridor","Manhattan",40.7080,-74.0110,["canyon of heroes","ticker tape parade","ticker-tape"]),
 ("k_town","Koreatown","landmark","Manhattan",40.7476,-73.9866,["koreatown","k-town"]),
 ("garment","The Garment District","landmark","Manhattan",40.7546,-73.9910,["garment district","the fashion district"]),
 ("diamond","The Diamond District","corridor","Manhattan",40.7570,-73.9790,["diamond district","47th street"]),
 ("chinatown_m","Chinatown","landmark","Manhattan",40.7158,-73.9970,["chinatown","mott street","doyers"]),
 ("little_italy","Little Italy","landmark","Manhattan",40.7191,-73.9973,["little italy","mulberry street","feast of san gennaro","san gennaro"]),
 ("alphabet_city","Alphabet City","landmark","Manhattan",40.7256,-73.9790,["alphabet city","tompkins square","avenue a","avenue b"]),
 ("meatpacking","The Meatpacking District","landmark","Manhattan",40.7404,-74.0080,["meatpacking"]),
 ("sugar_hill","Sugar Hill","landmark","Manhattan",40.8250,-73.9450,["sugar hill"]),
 ("el_barrio","El Barrio / Spanish Harlem","landmark","Manhattan",40.7957,-73.9389,["spanish harlem","el barrio","east harlem"]),
 ("hell_gate","Hell Gate","water","Manhattan",40.7830,-73.9210,["hell gate"]),
 ("harlem_river","The Harlem River","water","Manhattan",40.8200,-73.9330,["harlem river"]),
 ("hudson_river","The Hudson River","water","Manhattan",40.7700,-74.0100,["the hudson","hudson river"]),
 ("east_river","The East River","water","Manhattan",40.7350,-73.9700,["east river"]),
 ("ny_harbor","New York Harbor","water","Manhattan",40.6800,-74.0400,["new york harbor","ny harbor","the harbor","the narrows"]),

 # ---------- Brooklyn ----------
 ("brooklyn_bridge","The Brooklyn Bridge","bridge","Brooklyn",40.7061,-73.9969,["brooklyn bridge"]),
 ("manhattan_bridge","The Manhattan Bridge","bridge","Brooklyn",40.7075,-73.9903,["manhattan bridge"]),
 ("williamsburg_bridge","The Williamsburg Bridge","bridge","Brooklyn",40.7131,-73.9722,["williamsburg bridge"]),
 ("verrazzano","The Verrazzano-Narrows Bridge","bridge","Staten Island",40.6066,-74.0447,["verrazzano","verrazano"]),
 ("coney","Coney Island","landmark","Brooklyn",40.5749,-73.9857,["coney island","the cyclone","wonder wheel","nathan's","the boardwalk","luna park","the parachute jump","mermaid parade"]),
 ("brighton","Brighton Beach","landmark","Brooklyn",40.5776,-73.9614,["brighton beach","little odessa","the banya"]),
 ("prospect_park","Prospect Park","park","Brooklyn",40.6602,-73.9690,["prospect park","the long meadow","vale of cashmere","the drummers circle","grand army plaza"]),
 ("bk_museum","The Brooklyn Museum","institution","Brooklyn",40.6712,-73.9636,["brooklyn museum","botanic garden","cherry blossom festival"]),
 ("barclays","Barclays Center","venue","Brooklyn",40.6826,-73.9754,["barclays","the nets"]),
 ("ebbets","Ebbets Field","venue","Brooklyn",40.6650,-73.9570,["ebbets field","the dodgers","brooklyn dodgers"]),
 ("marcy","Marcy Houses","landmark","Brooklyn",40.6975,-73.9440,["marcy projects","marcy houses"]),
 ("dumbo","DUMBO","landmark","Brooklyn",40.7033,-73.9881,["dumbo","the manhattan bridge archway","washington street"]),
 ("bk_heights_prom","The Brooklyn Heights Promenade","landmark","Brooklyn",40.6960,-73.9977,["promenade","brooklyn heights"]),
 ("navy_yard","The Brooklyn Navy Yard","landmark","Brooklyn",40.7000,-73.9700,["navy yard"]),
 ("greenwood","Green-Wood Cemetery","park","Brooklyn",40.6520,-73.9930,["green-wood","greenwood cemetery"]),
 ("eastern_pkwy","Eastern Parkway","corridor","Brooklyn",40.6710,-73.9500,["eastern parkway","the west indian day parade","west indian day","j'ouvert","labor day parade"]),
 ("flatbush_ave","Flatbush Avenue","corridor","Brooklyn",40.6500,-73.9580,["flatbush avenue","flatbush ave"]),
 ("atlantic_ave","Atlantic Avenue","corridor","Brooklyn",40.6880,-73.9800,["atlantic avenue","atlantic ave"]),
 ("atlantic_tunnel","Atlantic Avenue Tunnel","landmark","Brooklyn",40.6883,-73.9945,["atlantic avenue tunnel","tunnel under atlantic avenue","cobble hill tunnel","oldest subway tunnel"]),
 ("bedford_ave","Bedford Avenue","corridor","Brooklyn",40.7150,-73.9570,["bedford avenue","bedford ave"]),
 ("kings_theatre","Kings Theatre","venue","Brooklyn",40.6490,-73.9570,["kings theatre"]),
 ("gowanus","The Gowanus Canal","water","Brooklyn",40.6740,-73.9930,["gowanus"]),
 ("red_hook_b","Red Hook","landmark","Brooklyn",40.6770,-74.0100,["red hook"]),
 ("junior_s","Junior's","venue","Brooklyn",40.6900,-73.9820,["junior's"]),
 ("floyd_bennett","Floyd Bennett Field","park","Brooklyn",40.5900,-73.8900,["floyd bennett"]),
 ("jamaica_bay","Jamaica Bay","water","Brooklyn",40.6100,-73.8300,["jamaica bay"]),

 # ---------- Queens ----------
 ("citi_field","Citi Field","venue","Queens",40.7571,-73.8458,["citi field","the mets","shea stadium","home run apple"]),
 ("shea","Shea Stadium","venue","Queens",40.7550,-73.8460,["shea"]),
 ("flushing_meadows","Flushing Meadows-Corona Park","park","Queens",40.7460,-73.8450,["flushing meadows","the unisphere","unisphere","world's fair","worlds fair","us open","arthur ashe"]),
 ("queensboro_bridge","The Queensboro Bridge","bridge","Queens",40.7570,-73.9540,["queensboro","59th street bridge","ed koch bridge"]),
 ("queensbridge","Queensbridge Houses","landmark","Queens",40.7560,-73.9450,["queensbridge"]),
 ("jfk","JFK Airport","transit","Queens",40.6413,-73.7781,["jfk","kennedy airport","airtrain"]),
 ("lga","LaGuardia Airport","transit","Queens",40.7769,-73.8740,["laguardia airport","lga"]),
 ("rockaway_beach","Rockaway Beach","landmark","Queens",40.5872,-73.8155,["rockaway","the rockaways","riis park","fort tilden"]),
 ("moma_ps1","MoMA PS1","institution","Queens",40.7455,-73.9470,["ps1","ps 1"]),
 ("5pointz","5Pointz","landmark","Queens",40.7440,-73.9420,["5pointz","five pointz"]),
 ("roosevelt_ave","Roosevelt Avenue","corridor","Queens",40.7490,-73.8800,["roosevelt avenue","under the 7 train","the 7 line elevated"]),
 ("steinway","Steinway Street","corridor","Queens",40.7620,-73.9200,["steinway street","little egypt"]),
 ("northern_blvd","Northern Boulevard","corridor","Queens",40.7550,-73.8700,["northern boulevard","northern blvd"]),
 ("kaufman","Kaufman Astoria Studios","venue","Queens",40.7560,-73.9230,["kaufman astoria","silvercup"]),
 ("aqueduct","Aqueduct Racetrack","venue","Queens",40.6720,-73.8330,["aqueduct"]),
 ("lefrak","LeFrak City","landmark","Queens",40.7350,-73.8630,["lefrak"]),
 ("hollis_q","Hollis","landmark","Queens",40.7110,-73.7620,["hollis","run-dmc","run dmc"]),
 ("st_albans_q","St. Albans","landmark","Queens",40.6890,-73.7650,["st. albans","st albans"]),
 ("ozone_park","Ozone Park","landmark","Queens",40.6790,-73.8430,["ozone park"]),

 # ---------- Bronx ----------
 ("yankee_stadium","Yankee Stadium","venue","Bronx",40.8296,-73.9262,["yankee stadium","the yankees","the bronx bombers","bleacher creatures","sultan of swat","the bronx bombers"]),
 ("sedgwick","1520 Sedgwick Avenue","landmark","Bronx",40.8420,-73.9280,["sedgwick","kool herc","the birth of hip-hop","1520 sedgwick"]),
 ("grand_concourse","The Grand Concourse","corridor","Bronx",40.8400,-73.9100,["grand concourse"]),
 ("arthur_ave","Arthur Avenue","corridor","Bronx",40.8550,-73.8870,["arthur avenue","belmont","the real little italy"]),
 ("bronx_zoo","The Bronx Zoo","park","Bronx",40.8506,-73.8770,["bronx zoo"]),
 ("botanical","The New York Botanical Garden","park","Bronx",40.8620,-73.8800,["botanical garden"]),
 ("orchard_beach","Orchard Beach","park","Bronx",40.8670,-73.7900,["orchard beach","the bronx riviera","pelham bay"]),
 ("city_island","City Island","island","Bronx",40.8470,-73.7870,["city island"]),
 ("fordham_u","Fordham","institution","Bronx",40.8620,-73.8850,["fordham"]),
 ("woodlawn","Woodlawn Cemetery","park","Bronx",40.8890,-73.8730,["woodlawn"]),
 ("hunts_point_b","Hunts Point","landmark","Bronx",40.8110,-73.8840,["hunts point","the produce market","the terminal market"]),
 ("co_op_city_b","Co-op City","landmark","Bronx",40.8740,-73.8290,["co-op city","co op city"]),
 ("gwb","The George Washington Bridge","bridge","Manhattan",40.8517,-73.9527,["george washington bridge","the gwb","the little red lighthouse"]),
 ("cross_bronx","The Cross Bronx Expressway","corridor","Bronx",40.8450,-73.9000,["cross bronx","robert moses expressway"]),
 ("rikers","Rikers Island","island","Bronx",40.7930,-73.8860,["rikers"]),

 # ---------- Staten Island ----------
 ("si_ferry","The Staten Island Ferry","transit","Staten Island",40.6437,-74.0736,["staten island ferry","the ferry"]),
 ("shaolin","Shaolin / Park Hill","landmark","Staten Island",40.6100,-74.0800,["shaolin","wu-tang","wu tang","park hill"]),
 ("snug_harbor","Snug Harbor","landmark","Staten Island",40.6430,-74.1020,["snug harbor"]),
 ("fresh_kills","Freshkills Park","park","Staten Island",40.5780,-74.1860,["fresh kills","freshkills"]),
 ("si_mall","The Staten Island Mall","landmark","Staten Island",40.5820,-74.1650,["staten island mall"]),

 # ---------- systemic / citywide but locatable ----------
 ("subway_system","The Subway","transit","Citywide",40.7420,-73.9890,["the subway","subway platform","subway car","the turnstile","turnstiles","the mta","mta","straphanger","the token booth","metrocard","omny","tap-to-pay","the swipe","subway stairs","the third rail","showtime","subway rat","the L train shutdown"]),
]

# subway lines: representative anchor points along the route
LINES = [
 ("line_1","The 1 Train","line","Manhattan",40.7900,-73.9740,["the 1 train","1 train"]),
 ("line_2","The 2 Train","line","Bronx",40.8300,-73.9200,["the 2 train","2 train"]),
 ("line_3","The 3 Train","line","Brooklyn",40.6700,-73.9200,["the 3 train","3 train"]),
 ("line_4","The 4 Train","line","Bronx",40.8290,-73.9260,["the 4 train","4 train"]),
 ("line_5","The 5 Train","line","Bronx",40.8500,-73.8800,["the 5 train","5 train"]),
 ("line_6","The 6 Train","line","Manhattan",40.7770,-73.9520,["the 6 train","6 train","the lex"]),
 ("line_7","The 7 Train","line","Queens",40.7490,-73.8700,["the 7 train","7 train","international express","the 7 line","the 7"]),
 ("line_a","The A Train","line","Manhattan",40.7553,-73.9895,["the a train","a train","take the a train"]),
 ("line_b","The B Train","line","Bronx",40.8500,-73.9000,["the b train","b train"]),
 ("line_c","The C Train","line","Brooklyn",40.6870,-73.9750,["the c train","c train"]),
 ("line_d","The D Train","line","Bronx",40.8600,-73.8900,["the d train","d train"]),
 ("line_e","The E Train","line","Queens",40.7300,-73.8300,["the e train","e train"]),
 ("line_f","The F Train","line","Brooklyn",40.6400,-73.9800,["the f train","f train"]),
 ("line_g","The G Train","line","Brooklyn",40.7100,-73.9500,["the g train","g train"]),
 ("line_j","The J Train","line","Brooklyn",40.6950,-73.9200,["the j train","j train","the jz","j/z"]),
 ("line_l","The L Train","line","Brooklyn",40.7070,-73.9230,["the l train","l train","the canarsie tube"]),
 ("line_m","The M Train","line","Queens",40.7000,-73.9000,["the m train","m train"]),
 ("line_n","The N Train","line","Brooklyn",40.6200,-73.9800,["the n train","n train"]),
 ("line_q","The Q Train","line","Brooklyn",40.5900,-73.9600,["the q train","q train"]),
 ("line_r","The R Train","line","Brooklyn",40.6400,-74.0200,["the r train","r train"]),
 ("line_s","The Shuttle","line","Manhattan",40.7560,-73.9830,["the shuttle","42nd street shuttle","the s train"]),
 ("line_z","The Z Train","line","Queens",40.6950,-73.8300,["the z train"]),
 ("sir","The Staten Island Railway","line","Staten Island",40.5800,-74.1200,["staten island railway"]),
]

BOROUGHS = [
 ("boro_manhattan","Manhattan","borough","Manhattan",40.7580,-73.9760,["manhattan","the island","the city proper"]),
 ("boro_brooklyn","Brooklyn","borough","Brooklyn",40.6500,-73.9500,["brooklyn","kings county","bk"]),
 ("boro_queens","Queens","borough","Queens",40.7280,-73.7940,["queens","queens county"]),
 ("boro_bronx","The Bronx","borough","Bronx",40.8500,-73.8700,["the bronx","bronx","boogie down"]),
 ("boro_staten","Staten Island","borough","Staten Island",40.5800,-74.1500,["staten island","richmond county"]),
]

# Neighborhood aliases mapping alias -> canonical NTA display name
NTA_ALIASES = {
 "bed-stuy":"Bedford-Stuyvesant","bedstuy":"Bedford-Stuyvesant","bed stuy":"Bedford-Stuyvesant",
 "les":"Lower East Side","the lower east side":"Lower East Side",
 "soho":"SoHo","noho":"SoHo","tribeca":"Tribeca","nolita":"SoHo",
 "the village":"Greenwich Village","greenwich village":"Greenwich Village","west village":"West Village",
 "east village":"East Village","the east village":"East Village",
 "ues":"Upper East Side","upper east side":"Upper East Side","carnegie hill":"Upper East Side","yorkville":"Upper East Side","lenox hill":"Upper East Side",
 "uws":"Upper West Side","upper west side":"Upper West Side","manhattan valley":"Upper West Side","lincoln square":"Upper West Side",
 "hell's kitchen":"Hell's Kitchen","hells kitchen":"Hell's Kitchen","clinton":"Hell's Kitchen",
 "midtown":"Midtown","the flatiron district":"Flatiron","flatiron district":"Flatiron","gramercy":"Gramercy",
 "murray hill":"Murray Hill","kips bay":"Murray Hill","turtle bay":"Turtle Bay",
 "fidi":"Financial District","financial district":"Financial District","battery park city":"Financial District",
 "chelsea":"Chelsea","morningside heights":"Morningside Heights","harlem":"Harlem","west harlem":"Manhattanville",
 "hamilton heights":"Hamilton Heights","washington heights":"Washington Heights","inwood":"Inwood","marble hill":"Marble Hill",
 "williamsburg":"Williamsburg","south williamsburg":"Williamsburg","east williamsburg":"East Williamsburg",
 "greenpoint":"Greenpoint","bushwick":"Bushwick","ridgewood":"Ridgewood","maspeth":"Maspeth",
 "crown heights":"Crown Heights","prospect heights":"Prospect Heights","park slope":"Park Slope","south slope":"Windsor Terrace",
 "windsor terrace":"Windsor Terrace","kensington":"Kensington","ditmas park":"Ditmas Park","flatbush":"Flatbush",
 "east flatbush":"East Flatbush","midwood":"Midwood","canarsie":"Canarsie","brownsville":"Brownsville",
 "east new york":"East New York","ocean hill":"Ocean Hill","cypress hills":"Cypress Hills","bay ridge":"Bay Ridge",
 "sunset park":"Sunset Park","borough park":"Borough Park","bensonhurst":"Bensonhurst","dyker heights":"Dyker Heights",
 "sheepshead bay":"Sheepshead Bay","gravesend":"Gravesend","gerritsen beach":"Sheepshead Bay","marine park":"Marine Park",
 "mill basin":"Marine Park","flatlands":"Flatlands","carroll gardens":"Carroll Gardens","cobble hill":"Carroll Gardens",
 "boerum hill":"Downtown Brooklyn","downtown brooklyn":"Downtown Brooklyn","fort greene":"Fort Greene","clinton hill":"Clinton Hill",
 "bushwick avenue":"Bushwick","prospect lefferts":"Prospect Lefferts Gardens","lefferts gardens":"Prospect Lefferts Gardens",
 "astoria":"Astoria","ditmars":"Astoria","long island city":"Long Island City","lic":"Long Island City","hunters point":"Long Island City",
 "sunnyside":"Sunnyside","woodside":"Woodside","jackson heights":"Jackson Heights","elmhurst":"Elmhurst","corona":"Corona",
 "east elmhurst":"East Elmhurst","rego park":"Rego Park","forest hills":"Forest Hills","kew gardens":"Kew Gardens",
 "richmond hill":"Richmond Hill","woodhaven":"Woodhaven","glendale":"Glendale","middle village":"Middle Village",
 "flushing":"Flushing","whitestone":"Whitestone","college point":"College Point","bayside":"Bayside","douglaston":"Douglaston",
 "little neck":"Douglaston","fresh meadows":"Fresh Meadows","jamaica":"Jamaica","south jamaica":"South Jamaica",
 "jamaica estates":"Jamaica Estates","queens village":"Queens Village","cambria heights":"Cambria Heights",
 "springfield gardens":"Springfield Gardens","laurelton":"Laurelton","rosedale":"Rosedale","howard beach":"Howard Beach",
 "far rockaway":"Far Rockaway","broad channel":"Broad Channel","belle harbor":"Rockaway Park","rockaway park":"Rockaway Park",
 "mott haven":"Mott Haven","port morris":"Mott Haven","melrose":"Melrose","morrisania":"Morrisania","hunts point":"Hunts Point",
 "longwood":"Longwood","highbridge":"Highbridge","concourse":"Concourse","fordham":"Fordham","belmont":"Belmont",
 "tremont":"Tremont","university heights":"University Heights","kingsbridge":"Kingsbridge","riverdale":"Riverdale",
 "spuyten duyvil":"Riverdale","norwood":"Norwood","bedford park":"Bedford Park","williamsbridge":"Williamsbridge",
 "wakefield":"Wakefield","woodlawn":"Wakefield","eastchester":"Eastchester","baychester":"Eastchester","co-op city":"Co-op City",
 "throgs neck":"Throgs Neck","country club":"Pelham Bay","morris park":"Morris Park","pelham parkway":"Pelham Parkway",
 "parkchester":"Parkchester","castle hill":"Castle Hill","soundview":"Soundview","clason point":"Soundview",
 "st. george":"St. George","st george":"St. George","stapleton":"Stapleton","tompkinsville":"Stapleton",
 "new brighton":"St. George","port richmond":"Port Richmond","west brighton":"West New Brighton","todt hill":"Todt Hill",
 "great kills":"Great Kills","new dorp":"New Dorp","midland beach":"New Dorp","south beach":"South Beach",
 "tottenville":"Tottenville","annadale":"Annadale","eltingville":"Great Kills","arden heights":"Arden Heights",
 "rossville":"Arden Heights","charleston":"Tottenville","willowbrook":"New Springville","bulls head":"New Springville",
 "new springville":"New Springville","mariners harbor":"Mariners Harbor","graniteville":"Mariners Harbor",
}

# NTA name -> clean display name (collapses the (North)/(East) splits)
def clean_nta(name):
    import re
    n = re.sub(r"\s*\((?:Central|North|South|East|West|Lower)\)", "", name).strip()
    n = n.split('-')[0].strip() if '-' in n and n not in (
        "Bedford-Stuyvesant","Green-Wood Cemetery","Co-op City","Prospect Lefferts Gardens-Wingate",
        "Mott Haven-Port Morris","Crown Heights","Bay Terrace-Clearview") else n
    fixes = {
      "Bedford":"Bedford-Stuyvesant","Bedford Park":"Bedford Park",
      "Prospect Lefferts Gardens-Wingate":"Prospect Lefferts Gardens",
      "Mott Haven-Port Morris":"Mott Haven",
      "Carroll Gardens":"Carroll Gardens","Downtown Brooklyn":"Downtown Brooklyn",
      "SoHo":"SoHo","Tribeca":"Tribeca","Midtown South":"Flatiron","Midtown":"Midtown",
      "Upper East Side":"Upper East Side","Upper West Side":"Upper West Side",
      "Chelsea":"Chelsea","Financial District":"Financial District","Chinatown":"Chinatown",
      "Hamilton Heights":"Hamilton Heights","Manhattanville":"Manhattanville",
      "Murray Hill":"Murray Hill","East Midtown":"Turtle Bay","Stuyvesant Town":"Stuyvesant Town",
      "The Battery":"The Battery","Sheepshead Bay":"Sheepshead Bay","Marine Park":"Marine Park",
      "Flatbush (West)":"Ditmas Park","Old Astoria":"Astoria","Queensbridge":"Queensbridge",
      "Long Island City":"Long Island City","Breezy Point":"Rockaway Park","Rockaway Beach":"Rockaway Beach",
      "Jacob Riis Park":"Riis Park","Springfield Gardens (North)":"Springfield Gardens",
      "Kingsbridge Heights":"Kingsbridge","Kingsbridge":"Kingsbridge","Riverdale":"Riverdale",
      "Pelham Bay":"Pelham Bay","Eastchester":"Eastchester","Wakefield":"Wakefield",
      "Mariner's Harbor":"Mariners Harbor","St. George":"St. George","Tompkinsville":"Stapleton",
      "West New Brighton":"West New Brighton","Grasmere":"South Beach","Oakwood":"Oakwood",
      "Annadale":"Annadale","Arden Heights":"Arden Heights","Great Kills":"Great Kills",
      "New Springville":"New Springville","Todt Hill":"Todt Hill","Tottenville":"Tottenville",
      "Glen Oaks":"Glen Oaks","Oakland Gardens":"Oakland Gardens","Pomonok":"Pomonok",
      "Douglaston":"Douglaston","Bay Terrace-Clearview":"Bay Terrace","Murray Hill (Queens)":"Murray Hill",
      "Fordham Heights":"Fordham","University Heights":"University Heights","Mount Eden":"Mount Eden",
      "Claremont Village":"Claremont","Soundview":"Soundview","Throgs Neck":"Throgs Neck",
      "Jamaica Estates":"Jamaica Estates","Jamaica Hills":"Jamaica Hills","Far Rockaway":"Far Rockaway",
      "Ozone Park (North)":"Ozone Park","Sunset Park":"Sunset Park","Bushwick":"Bushwick",
      "Astoria":"Astoria","Harlem":"Harlem","East Harlem":"East Harlem","Washington Heights":"Washington Heights",
      "Bushwick (East)":"Bushwick","Gravesend":"Gravesend","East Flatbush":"East Flatbush",
      "East New York":"East New York","Spring Creek":"Spring Creek","Highland Park":"Highland Park",
      "Flushing":"Flushing","Corona":"Corona","North Corona":"Corona","Concourse":"Concourse",
      "Crown Heights":"Crown Heights","Bay Ridge":"Bay Ridge","Yankee Stadium":"Concourse",
    }
    return fixes.get(n, n)
