#!/usr/bin/env python3
"""Regenerate src/used.ts from the latest export manifest so fresh rooms avoid pieces already on a wall.
  python3 used_pieces.py [path/to/manifest.json]"""
import json, sys, os, glob
HERE=os.path.dirname(os.path.abspath(__file__)); ROOT=os.path.abspath(os.path.join(HERE,'..','..','..'))
p=sys.argv[1] if len(sys.argv)>1 else sorted(glob.glob(os.path.join(ROOT,'MUSEUM EXPORTS','*','manifest.json')))[-1]
m=json.load(open(p)); used=sorted({h['n'] for r in m['rooms'] for h in r['hang'] if h.get('n')})
open(os.path.join(HERE,'src/used.ts'),'w').write("/* Generated by used_pieces.py from "+os.path.relpath(p,ROOT)+": every piece hung in an exported room on that day.\n   Rooms with `fresh: true` in CURATION push these to the back so new rooms show New Yorkers the museum has not shown. */\nexport const USED = new Set<number>(["+",".join(map(str,used))+"]);\n")
print(len(used),'used pieces from',os.path.relpath(p,ROOT))
