#!/usr/bin/env python3
"""new-rooms.html: a visual index of every room added after the first 111, generated from rooms.json.
Runs inside build_all.sh after rooms_registry.py; build_seo.py then injects the seo block."""
import json, os, html
HERE = os.path.dirname(os.path.abspath(__file__)); SITE = os.path.dirname(HERE)
rooms = [r for r in json.load(open(os.path.join(HERE, "rooms.json"))) if r["index"] >= 112]
first, last = rooms[0]["index"], rooms[-1]["index"]
def e(s): return html.escape(s, quote=True)
cards = "".join(f'<a class="card" href="museum.html#room={r["id"]}&hang=place"><img src="assets/museum/rooms/{r["id"]}.jpg" alt="{e(r["name"])} virtual gallery" loading="lazy"><div><small>{r["index"]} / {e(r["area"])}</small><h2>{e(r["name"])}</h2><p>{e(r["description"])}</p><span>Enter gallery ↗</span></div></a>' for r in rooms)
page = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>The new rooms · NEW YORKERS by MLow</title><style>*{{box-sizing:border-box}}body{{margin:0;background:#090e16;color:#eee9dd;font-family:Arial,sans-serif}}main{{max-width:1280px;margin:auto;padding:48px 28px}}small{{font-size:10px;letter-spacing:.15em;color:#98b7bd}}h1{{font:normal clamp(44px,7vw,88px)/1 Georgia;max-width:800px;margin:26px 0}}header p{{color:#a9b3bf;max-width:660px;line-height:1.7;margin-bottom:44px}}.grid{{display:grid;grid-template-columns:1fr 1fr;gap:28px}}.card{{color:inherit;text-decoration:none;background:#101923;border:1px solid #25303b}}.card img{{display:block;width:100%;aspect-ratio:16/9;object-fit:cover}}.card div{{padding:26px}}.card h2{{font:normal 30px Georgia;margin:16px 0}}.card p{{color:#a9b3bf;line-height:1.6;min-height:52px}}.card span{{display:block;color:#98d4d7;margin-top:22px}}.card:hover{{border-color:#98d4d7}}.card:focus-visible{{outline:3px solid #98d4d7}}nav a{{color:#98d4d7}}footer{{padding-top:45px;color:#8795a3;font-size:13px}}@media(max-width:650px){{.grid{{grid-template-columns:1fr}}main{{padding:30px 18px}}.card div{{padding:22px}}}}</style></head><main><header><small>NEW YORKERS // BY MLOW · ROOMS {first} TO {last}</small><h1>The city behind<br>the city.</h1><p>{len(rooms)} rooms added to THE MUSEUM after the first 111: ten working worlds imagined around the collection, the people, the labor, the unseen systems, and fifteen landmarks from Katz's to Hamilton Grange. Pick a room, then walk, inspect each work, or take the guided tour.</p><nav><a href="museum.html">Back to THE MUSEUM</a></nav></header><div class="grid">{cards}</div><footer>Every room hangs the painted New Yorkers that belong to it. The interiors are original speculative spaces and interpretive landmark adaptations, not measured reconstructions.</footer></main><script src="assets/eggs.js" defer></script></html>'''
open(os.path.join(SITE, "new-rooms.html"), "w", encoding="utf-8").write(page)
print(f"new-rooms.html: {len(rooms)} rooms ({first} to {last})")
