#!/usr/bin/env python3
"""Writes app/logos.js: the two marks burned into every saved piece, as data URIs.

  MLOW       the evil eye wordmark, white, from NEW YORKERS SITE/assets/brand/logo_white.png
  N3W        the N3W YORKERS // BY MLow wordmark, from assets/brand/logos/n3w-02.png. That master is a
             dark logo on a light plate, so the plate becomes transparent and the near black letters
             become cloud white; the blue eye, the skyline and the pink // keep their colour.

Data URIs and not files because a canvas that draws an image from another origin (or from file://)
refuses to export, and SAVE has to work however the page is opened. Run it again only if a logo changes:
  python3 tools/make_logos.py [path to NEW YORKERS SITE]
"""
import base64, io, os, sys
import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__)); REPO = os.path.dirname(HERE)
SITE = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(os.path.dirname(REPO)), "NEW YORKERS SITE")
BRAND = os.path.join(SITE, "assets", "brand")


def png_uri(im):
    b = io.BytesIO(); im.save(b, "PNG", optimize=True)
    return "data:image/png;base64," + base64.b64encode(b.getvalue()).decode()


def crop(im):
    return im.crop(im.getbbox())


mlow = crop(Image.open(os.path.join(BRAND, "logo_white.png")).convert("RGBA"))
mlow = mlow.resize((600, round(600 * mlow.height / mlow.width)), Image.LANCZOS)

src = np.asarray(Image.open(os.path.join(BRAND, "logos", "n3w-02.png")).convert("RGB")).astype(float)
alpha = np.clip(((255 - src.min(axis=2)) - 18) / 60, 0, 1)
rgb = src.copy()
rgb[(src.max(axis=2) - src.min(axis=2)) < 60] = [240, 244, 248]
n3w = crop(Image.fromarray(np.dstack([rgb, alpha * 255]).astype(np.uint8)))

out = os.path.join(REPO, "app", "logos.js")
open(out, "w").write(
    "/* Generated by tools/make_logos.py. The marks on every saved piece: MLOW and N3W YORKERS, white on clear. */\n"
    f"window.MK_LOGOS = {{ mlow: '{png_uri(mlow)}', n3w: '{png_uri(n3w)}' }};\n")
print(f"logos.js: mlow {mlow.size}, n3w {n3w.size}, {os.path.getsize(out) // 1024} KB")
